###############################################################
#  Generated by:      Cadence Innovus 25.10-p002_1
#  OS:                Linux x86_64(Host ID tallinn.emse.fr)
#  Generated on:      Thu Aug 20 17:48:11 2026
#  Design:            top
#  Command:           write_db /home/edu4chip_18/project_calendar/layout/top_XH180/checkpoint/top_3.enc
###############################################################
current_design top
set_units -time 1ns -capacitance 1pf
#END OF CLOCK SECTION#
set_load -pin_load -max  0.045  [get_ports {tx}]
set_load -pin_load -min  0.045  [get_ports {tx}]
