/*
###############################################################
#  Generated by:      Cadence Innovus 25.10-p002_1
#  OS:                Linux x86_64(Host ID tallinn.emse.fr)
#  Generated on:      Thu Aug 20 18:00:13 2026
#  Design:            top
#  Command:           write_netlist /home/edu4chip_18/project_calendar/layout/top_XH180/top_lyt.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 25.10-p002_1
// Generated on: Aug 20 2026 17:39:56 CEST (Aug 20 2026 15:39:56 UTC)
// Verification Directory fv/top 
module chklpyr (
	year_12, 
	year_34, 
	is_leap_year);
   input [7:0] year_12;
   input [7:0] year_34;
   output is_leap_year;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;

   AN311HDX0 g211__2398 (.A(n_0),
	.B(n_2),
	.C(n_3),
	.D(year_34[1]),
	.E(year_34[0]),
	.Q(is_leap_year));
   NO3HDX0 g212__5107 (.A(n_1),
	.B(year_34[7]),
	.C(year_34[6]),
	.Q(n_3));
   NO2HDX0 g213__6260 (.A(year_34[3]),
	.B(year_34[2]),
	.Q(n_2));
   NO2HDX0 g214__4319 (.A(year_12[1]),
	.B(year_12[0]),
	.Q(n_1));
   NO2HDX0 g215__8428 (.A(year_34[5]),
	.B(year_34[4]),
	.Q(n_0));
endmodule

module lut_month (
	month, 
	month_lut);
   input [7:0] month;
   output [7:0] month_lut;

   // Internal wires
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;

   AN21HDX0 g414__5526 (.A(n_10),
	.B(n_12),
	.C(n_7),
	.Q(month_lut[2]));
   NO2HDX0 g415__6783 (.A(n_9),
	.B(n_7),
	.Q(month_lut[1]));
   NO2I1HDX0 g416__3680 (.AN(n_11),
	.B(n_7),
	.Q(month_lut[0]));
   ON21HDX0 g417__1617 (.A(n_8),
	.B(n_2),
	.C(month[0]),
	.Q(n_12));
   ON32HDX0 g418__2802 (.A(month[1]),
	.B(month[0]),
	.C(n_3),
	.D(n_5),
	.E(n_4),
	.Q(n_11));
   AO211HDX0 g419__1705 (.A(n_3),
	.B(month[1]),
	.C(month[0]),
	.D(n_2),
	.Q(n_10));
   AN22HDX0 g420__5122 (.A(n_6),
	.B(month[1]),
	.C(n_1),
	.D(month[0]),
	.Q(n_9));
   NO2I1HDX0 g421__8246 (.AN(month[1]),
	.B(n_5),
	.Q(n_8));
   ON21HDX0 g422__7098 (.A(month[0]),
	.B(month[3]),
	.C(month[2]),
	.Q(n_6));
   OR4HDX0 g423__6131 (.A(month[4]),
	.B(month[7]),
	.C(month[6]),
	.D(month[5]),
	.Q(n_7));
   NO2I1HDX0 g424__1881 (.AN(month[0]),
	.B(month[1]),
	.Q(n_4));
   NA2I1HDX0 g425__5115 (.AN(month[3]),
	.B(month[2]),
	.Q(n_5));
   NO2HDX0 g426__7482 (.A(month[2]),
	.B(month[3]),
	.Q(n_1));
   NA2I1HDX0 g427__4733 (.AN(month[2]),
	.B(month[3]),
	.Q(n_3));
   NO2HDX0 g428__6161 (.A(month[2]),
	.B(month[1]),
	.Q(n_2));
endmodule

module lut_year (
	year_12, 
	year_12_lut);
   input [7:0] year_12;
   output [7:0] year_12_lut;

   NO2I1HDX0 g31__9315 (.AN(year_12[0]),
	.B(year_12[1]),
	.Q(year_12_lut[2]));
   NO2I1HDX0 g32__9945 (.AN(year_12[1]),
	.B(year_12[0]),
	.Q(year_12_lut[1]));
   OR2HDX0 g33__2883 (.A(year_12[0]),
	.B(year_12[1]),
	.Q(year_12_lut[0]));
endmodule

module mod7 (
	num_in, 
	mod_out);
   input [7:0] num_in;
   output [7:0] mod_out;

   // Internal wires
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;

   NO2HDX0 g800__2346 (.A(n_20),
	.B(n_17),
	.Q(mod_out[0]));
   AN311HDX0 g802__1666 (.A(n_8),
	.B(n_14),
	.C(n_16),
	.D(n_18),
	.E(n_19),
	.Q(mod_out[1]));
   EO2HDX0 g803__7410 (.A(n_16),
	.B(n_11),
	.Q(n_20));
   NO2HDX0 g805__6417 (.A(n_16),
	.B(n_8),
	.Q(n_19));
   NO2HDX0 g806__5477 (.A(n_17),
	.B(n_11),
	.Q(n_18));
   NO2HDX0 g807__2398 (.A(n_15),
	.B(n_5),
	.Q(n_17));
   NA2HDX0 g808__5107 (.A(n_15),
	.B(n_5),
	.Q(n_16));
   OA21HDX0 g809__6260 (.A(n_13),
	.B(n_9),
	.C(n_14),
	.Q(n_15));
   NA2HDX0 g810__4319 (.A(n_13),
	.B(n_9),
	.Q(n_14));
   HAHDX0 g812__8428 (.A(n_10),
	.B(n_6),
	.CO(n_13),
	.S(n_12));
   NA2I1HDX0 g813__5526 (.AN(n_8),
	.B(n_10),
	.Q(n_11));
   INHDX0 g814 (.A(n_7),
	.Q(n_8));
   FAHDX0 g815__6783 (.A(num_in[5]),
	.B(num_in[2]),
	.CI(n_2),
	.CO(n_9),
	.S(n_10));
   HAHDX0 g816__3680 (.A(n_3),
	.B(n_4),
	.CO(n_6),
	.S(n_7));
   FAHDX0 g817__1617 (.A(num_in[3]),
	.B(num_in[0]),
	.CI(num_in[6]),
	.CO(n_4),
	.S(n_5));
   FAHDX0 g818__2802 (.A(num_in[4]),
	.B(num_in[1]),
	.CI(num_in[7]),
	.CO(n_2),
	.S(n_3));
   NO22HDX0 g2__1705 (.A(n_19),
	.B(n_12),
	.C(n_18),
	.Q(mod_out[2]));
endmodule

module fca2005 (
	day, 
	month, 
	year_12, 
	year_34, 
	weekday);
   input [7:0] day;
   input [7:0] month;
   input [7:0] year_12;
   input [7:0] year_34;
   output [7:0] weekday;

   // Internal wires
   wire [7:0] lut_month_wire;
   wire [7:0] year_12_lut;
   wire [7:0] total_sum;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;
   wire UNCONNECTED7;
   wire UNCONNECTED8;
   wire UNCONNECTED9;
   wire UNCONNECTED10;
   wire UNCONNECTED11;
   wire UNCONNECTED12;
   wire UNCONNECTED13;
   wire UNCONNECTED_HIER_Z;
   wire UNCONNECTED_HIER_Z0;
   wire UNCONNECTED_HIER_Z1;
   wire UNCONNECTED_HIER_Z2;
   wire UNCONNECTED_HIER_Z3;
   wire UNCONNECTED_HIER_Z4;
   wire UNCONNECTED_HIER_Z5;
   wire UNCONNECTED_HIER_Z6;
   wire UNCONNECTED_HIER_Z7;
   wire UNCONNECTED_HIER_Z8;
   wire UNCONNECTED_HIER_Z9;
   wire UNCONNECTED_HIER_Z10;
   wire csa_tree_ADD_TC_OP_3_groupi_n_0;
   wire csa_tree_ADD_TC_OP_3_groupi_n_1;
   wire csa_tree_ADD_TC_OP_3_groupi_n_2;
   wire csa_tree_ADD_TC_OP_3_groupi_n_4;
   wire csa_tree_ADD_TC_OP_3_groupi_n_5;
   wire csa_tree_ADD_TC_OP_3_groupi_n_6;
   wire csa_tree_ADD_TC_OP_3_groupi_n_7;
   wire csa_tree_ADD_TC_OP_3_groupi_n_8;
   wire csa_tree_ADD_TC_OP_3_groupi_n_9;
   wire csa_tree_ADD_TC_OP_3_groupi_n_10;
   wire csa_tree_ADD_TC_OP_3_groupi_n_11;
   wire csa_tree_ADD_TC_OP_3_groupi_n_12;
   wire csa_tree_ADD_TC_OP_3_groupi_n_13;
   wire csa_tree_ADD_TC_OP_3_groupi_n_14;
   wire csa_tree_ADD_TC_OP_3_groupi_n_15;
   wire csa_tree_ADD_TC_OP_3_groupi_n_16;
   wire csa_tree_ADD_TC_OP_3_groupi_n_17;
   wire csa_tree_ADD_TC_OP_3_groupi_n_18;
   wire csa_tree_ADD_TC_OP_3_groupi_n_19;
   wire csa_tree_ADD_TC_OP_3_groupi_n_20;
   wire csa_tree_ADD_TC_OP_3_groupi_n_21;
   wire csa_tree_ADD_TC_OP_3_groupi_n_22;
   wire csa_tree_ADD_TC_OP_3_groupi_n_23;
   wire csa_tree_ADD_TC_OP_3_groupi_n_24;
   wire csa_tree_ADD_TC_OP_3_groupi_n_25;
   wire csa_tree_ADD_TC_OP_3_groupi_n_26;
   wire csa_tree_ADD_TC_OP_3_groupi_n_27;
   wire csa_tree_ADD_TC_OP_3_groupi_n_28;
   wire csa_tree_ADD_TC_OP_3_groupi_n_29;
   wire csa_tree_ADD_TC_OP_3_groupi_n_30;
   wire csa_tree_ADD_TC_OP_3_groupi_n_31;
   wire csa_tree_ADD_TC_OP_3_groupi_n_33;
   wire csa_tree_ADD_TC_OP_3_groupi_n_34;
   wire csa_tree_ADD_TC_OP_3_groupi_n_35;
   wire csa_tree_ADD_TC_OP_3_groupi_n_36;
   wire csa_tree_ADD_TC_OP_3_groupi_n_37;
   wire csa_tree_ADD_TC_OP_3_groupi_n_38;
   wire csa_tree_ADD_TC_OP_3_groupi_n_39;
   wire csa_tree_ADD_TC_OP_3_groupi_n_41;
   wire csa_tree_ADD_TC_OP_3_groupi_n_42;
   wire csa_tree_ADD_TC_OP_3_groupi_n_43;
   wire csa_tree_ADD_TC_OP_3_groupi_n_45;
   wire csa_tree_ADD_TC_OP_3_groupi_n_47;
   wire csa_tree_ADD_TC_OP_3_groupi_n_49;
   wire csa_tree_ADD_TC_OP_3_groupi_n_51;
   wire is_leap_year_wire;
   wire n_0;
   wire n_1;
   wire n_83;

   chklpyr chklpyr (.year_12({ UNCONNECTED_HIER_Z4,
		UNCONNECTED_HIER_Z3,
		UNCONNECTED_HIER_Z2,
		UNCONNECTED_HIER_Z1,
		UNCONNECTED_HIER_Z0,
		UNCONNECTED_HIER_Z,
		year_12[1],
		year_12[0] }),
	.year_34(year_34),
	.is_leap_year(is_leap_year_wire));
   lut_month lut_month (.month(month),
	.month_lut({ UNCONNECTED3,
		UNCONNECTED2,
		UNCONNECTED1,
		UNCONNECTED0,
		UNCONNECTED,
		lut_month_wire[2],
		lut_month_wire[1],
		lut_month_wire[0] }));
   lut_year lut_yearr (.year_12({ UNCONNECTED_HIER_Z10,
		UNCONNECTED_HIER_Z9,
		UNCONNECTED_HIER_Z8,
		UNCONNECTED_HIER_Z7,
		UNCONNECTED_HIER_Z6,
		UNCONNECTED_HIER_Z5,
		year_12[1],
		year_12[0] }),
	.year_12_lut({ UNCONNECTED8,
		UNCONNECTED7,
		UNCONNECTED6,
		UNCONNECTED5,
		UNCONNECTED4,
		year_12_lut[2],
		year_12_lut[1],
		year_12_lut[0] }));
   mod7 mod7_total (.num_in(total_sum),
	.mod_out({ UNCONNECTED13,
		UNCONNECTED12,
		UNCONNECTED11,
		UNCONNECTED10,
		UNCONNECTED9,
		weekday[2],
		weekday[1],
		weekday[0] }));
   NA4I3HDX0 g177__8246 (.AN(month[3]),
	.BN(month[4]),
	.CN(month[2]),
	.D(is_leap_year_wire),
	.Q(n_1));
   EO2HDX0 g178__7098 (.A(month[1]),
	.B(month[0]),
	.Q(n_0));
   EN3HDX0 csa_tree_ADD_TC_OP_3_groupi_g1227__6131 (.A(csa_tree_ADD_TC_OP_3_groupi_n_51),
	.B(csa_tree_ADD_TC_OP_3_groupi_n_29),
	.C(csa_tree_ADD_TC_OP_3_groupi_n_12),
	.Q(total_sum[7]));
   FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1228__1881 (.A(csa_tree_ADD_TC_OP_3_groupi_n_30),
	.B(csa_tree_ADD_TC_OP_3_groupi_n_37),
	.CI(csa_tree_ADD_TC_OP_3_groupi_n_49),
	.CO(csa_tree_ADD_TC_OP_3_groupi_n_51),
	.S(total_sum[6]));
   FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1229__5115 (.A(csa_tree_ADD_TC_OP_3_groupi_n_38),
	.B(csa_tree_ADD_TC_OP_3_groupi_n_33),
	.CI(csa_tree_ADD_TC_OP_3_groupi_n_47),
	.CO(csa_tree_ADD_TC_OP_3_groupi_n_49),
	.S(total_sum[5]));
   FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1230__7482 (.A(csa_tree_ADD_TC_OP_3_groupi_n_41),
	.B(csa_tree_ADD_TC_OP_3_groupi_n_34),
	.CI(csa_tree_ADD_TC_OP_3_groupi_n_45),
	.CO(csa_tree_ADD_TC_OP_3_groupi_n_47),
	.S(total_sum[4]));
   FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1231__4733 (.A(csa_tree_ADD_TC_OP_3_groupi_n_42),
	.B(csa_tree_ADD_TC_OP_3_groupi_n_35),
	.CI(csa_tree_ADD_TC_OP_3_groupi_n_43),
	.CO(csa_tree_ADD_TC_OP_3_groupi_n_45),
	.S(total_sum[3]));
   FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1232__6161 (.A(csa_tree_ADD_TC_OP_3_groupi_n_36),
	.B(csa_tree_ADD_TC_OP_3_groupi_n_25),
	.CI(csa_tree_ADD_TC_OP_3_groupi_n_39),
	.CO(csa_tree_ADD_TC_OP_3_groupi_n_43),
	.S(total_sum[2]));
   FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1233__9315 (.A(csa_tree_ADD_TC_OP_3_groupi_n_27),
	.B(csa_tree_ADD_TC_OP_3_groupi_n_8),
	.CI(csa_tree_ADD_TC_OP_3_groupi_n_24),
	.CO(csa_tree_ADD_TC_OP_3_groupi_n_41),
	.S(csa_tree_ADD_TC_OP_3_groupi_n_42));
   FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1234__9945 (.A(csa_tree_ADD_TC_OP_3_groupi_n_31),
	.B(csa_tree_ADD_TC_OP_3_groupi_n_15),
	.CI(csa_tree_ADD_TC_OP_3_groupi_n_26),
	.CO(csa_tree_ADD_TC_OP_3_groupi_n_39),
	.S(total_sum[1]));
   FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1235__2883 (.A(csa_tree_ADD_TC_OP_3_groupi_n_17),
	.B(csa_tree_ADD_TC_OP_3_groupi_n_1),
	.CI(csa_tree_ADD_TC_OP_3_groupi_n_22),
	.CO(csa_tree_ADD_TC_OP_3_groupi_n_37),
	.S(csa_tree_ADD_TC_OP_3_groupi_n_38));
   FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1236__2346 (.A(lut_month_wire[2]),
	.B(csa_tree_ADD_TC_OP_3_groupi_n_19),
	.CI(csa_tree_ADD_TC_OP_3_groupi_n_28),
	.CO(csa_tree_ADD_TC_OP_3_groupi_n_35),
	.S(csa_tree_ADD_TC_OP_3_groupi_n_36));
   FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1237__1666 (.A(csa_tree_ADD_TC_OP_3_groupi_n_18),
	.B(csa_tree_ADD_TC_OP_3_groupi_n_7),
	.CI(csa_tree_ADD_TC_OP_3_groupi_n_23),
	.CO(csa_tree_ADD_TC_OP_3_groupi_n_33),
	.S(csa_tree_ADD_TC_OP_3_groupi_n_34));
   FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1238__7410 (.A(csa_tree_ADD_TC_OP_3_groupi_n_16),
	.B(lut_month_wire[0]),
	.CI(n_83),
	.CO(csa_tree_ADD_TC_OP_3_groupi_n_31),
	.S(total_sum[0]));
   FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1239__6417 (.A(csa_tree_ADD_TC_OP_3_groupi_n_21),
	.B(day[5]),
	.CI(csa_tree_ADD_TC_OP_3_groupi_n_11),
	.CO(csa_tree_ADD_TC_OP_3_groupi_n_29),
	.S(csa_tree_ADD_TC_OP_3_groupi_n_30));
   FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1240__5477 (.A(csa_tree_ADD_TC_OP_3_groupi_n_5),
	.B(csa_tree_ADD_TC_OP_3_groupi_n_0),
	.CI(csa_tree_ADD_TC_OP_3_groupi_n_14),
	.CO(csa_tree_ADD_TC_OP_3_groupi_n_27),
	.S(csa_tree_ADD_TC_OP_3_groupi_n_28));
   FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1241__2398 (.A(csa_tree_ADD_TC_OP_3_groupi_n_20),
	.B(csa_tree_ADD_TC_OP_3_groupi_n_9),
	.CI(lut_month_wire[1]),
	.CO(csa_tree_ADD_TC_OP_3_groupi_n_25),
	.S(csa_tree_ADD_TC_OP_3_groupi_n_26));
   FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1242__5107 (.A(day[2]),
	.B(day[3]),
	.CI(csa_tree_ADD_TC_OP_3_groupi_n_13),
	.CO(csa_tree_ADD_TC_OP_3_groupi_n_23),
	.S(csa_tree_ADD_TC_OP_3_groupi_n_24));
   FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1243__6260 (.A(year_34[7]),
	.B(day[4]),
	.CI(year_34[5]),
	.CO(csa_tree_ADD_TC_OP_3_groupi_n_21),
	.S(csa_tree_ADD_TC_OP_3_groupi_n_22));
   FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1244__4319 (.A(year_12_lut[1]),
	.B(year_34[1]),
	.CI(csa_tree_ADD_TC_OP_3_groupi_n_6),
	.CO(csa_tree_ADD_TC_OP_3_groupi_n_19),
	.S(csa_tree_ADD_TC_OP_3_groupi_n_20));
   FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1245__8428 (.A(csa_tree_ADD_TC_OP_3_groupi_n_2),
	.B(year_34[6]),
	.CI(year_34[4]),
	.CO(csa_tree_ADD_TC_OP_3_groupi_n_17),
	.S(csa_tree_ADD_TC_OP_3_groupi_n_18));
   FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1246__5526 (.A(year_12_lut[0]),
	.B(day[0]),
	.CI(csa_tree_ADD_TC_OP_3_groupi_n_10),
	.CO(csa_tree_ADD_TC_OP_3_groupi_n_15),
	.S(csa_tree_ADD_TC_OP_3_groupi_n_16));
   FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1247__6783 (.A(year_34[4]),
	.B(year_34[2]),
	.CI(year_12_lut[2]),
	.CO(csa_tree_ADD_TC_OP_3_groupi_n_13),
	.S(csa_tree_ADD_TC_OP_3_groupi_n_14));
   EN3HDX0 csa_tree_ADD_TC_OP_3_groupi_g1248__3680 (.A(csa_tree_ADD_TC_OP_3_groupi_n_4),
	.B(year_34[7]),
	.C(day[7]),
	.Q(csa_tree_ADD_TC_OP_3_groupi_n_12));
   AO21HDX0 csa_tree_ADD_TC_OP_3_groupi_g1249__1617 (.A(day[6]),
	.B(year_34[6]),
	.C(csa_tree_ADD_TC_OP_3_groupi_n_4),
	.Q(csa_tree_ADD_TC_OP_3_groupi_n_11));
   NA22HDX0 csa_tree_ADD_TC_OP_3_groupi_g1250__2802 (.A(year_34[0]),
	.B(year_34[2]),
	.C(csa_tree_ADD_TC_OP_3_groupi_n_6),
	.Q(csa_tree_ADD_TC_OP_3_groupi_n_10));
   NA22HDX0 csa_tree_ADD_TC_OP_3_groupi_g1251__1705 (.A(day[1]),
	.B(year_34[3]),
	.C(csa_tree_ADD_TC_OP_3_groupi_n_5),
	.Q(csa_tree_ADD_TC_OP_3_groupi_n_9));
   NA22HDX0 csa_tree_ADD_TC_OP_3_groupi_g1252__5122 (.A(year_34[3]),
	.B(year_34[5]),
	.C(csa_tree_ADD_TC_OP_3_groupi_n_7),
	.Q(csa_tree_ADD_TC_OP_3_groupi_n_8));
   OR2HDX0 csa_tree_ADD_TC_OP_3_groupi_g1253__8246 (.A(year_34[5]),
	.B(year_34[3]),
	.Q(csa_tree_ADD_TC_OP_3_groupi_n_7));
   OR2HDX0 csa_tree_ADD_TC_OP_3_groupi_g1254__7098 (.A(year_34[2]),
	.B(year_34[0]),
	.Q(csa_tree_ADD_TC_OP_3_groupi_n_6));
   OR2HDX0 csa_tree_ADD_TC_OP_3_groupi_g1255__6131 (.A(year_34[3]),
	.B(day[1]),
	.Q(csa_tree_ADD_TC_OP_3_groupi_n_5));
   NO2HDX0 csa_tree_ADD_TC_OP_3_groupi_g1256__1881 (.A(year_34[6]),
	.B(day[6]),
	.Q(csa_tree_ADD_TC_OP_3_groupi_n_4));
   INHDX0 csa_tree_ADD_TC_OP_3_groupi_g1258 (.A(day[4]),
	.Q(csa_tree_ADD_TC_OP_3_groupi_n_2));
   INHDX0 csa_tree_ADD_TC_OP_3_groupi_g1259 (.A(day[5]),
	.Q(csa_tree_ADD_TC_OP_3_groupi_n_1));
   INHDX0 csa_tree_ADD_TC_OP_3_groupi_g1260 (.A(day[2]),
	.Q(csa_tree_ADD_TC_OP_3_groupi_n_0));
   NA5I4HDX0 g2 (.AN(month[7]),
	.BN(month[5]),
	.CN(n_1),
	.DN(month[6]),
	.E(n_0),
	.Q(n_83));
endmodule

module funky_cu (
	clk, 
	rst_n, 
	din, 
	dout, 
	done_reading, 
	juanito_data_available, 
	write_result, 
	FE_OFN1_clk);
   input clk;
   input rst_n;
   input [31:0] din;
   output [7:0] dout;
   output done_reading;
   input juanito_data_available;
   output write_result;
   input FE_OFN1_clk;

   // Internal wires
   wire [31:0] data_buf;
   wire [2:0] p_state;
   wire UNCONNECTED14;
   wire UNCONNECTED15;
   wire UNCONNECTED16;
   wire UNCONNECTED17;
   wire UNCONNECTED18;
   wire UNCONNECTED_HIER_Z11;
   wire UNCONNECTED_HIER_Z12;
   wire UNCONNECTED_HIER_Z13;
   wire UNCONNECTED_HIER_Z14;
   wire UNCONNECTED_HIER_Z15;
   wire UNCONNECTED_HIER_Z16;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;

   fca2005 fca2005 (.day({ data_buf[7],
		data_buf[6],
		data_buf[5],
		data_buf[4],
		data_buf[3],
		data_buf[2],
		data_buf[1],
		data_buf[0] }),
	.month({ data_buf[15],
		data_buf[14],
		data_buf[13],
		data_buf[12],
		data_buf[11],
		data_buf[10],
		data_buf[9],
		data_buf[8] }),
	.year_12({ UNCONNECTED_HIER_Z16,
		UNCONNECTED_HIER_Z15,
		UNCONNECTED_HIER_Z14,
		UNCONNECTED_HIER_Z13,
		UNCONNECTED_HIER_Z12,
		UNCONNECTED_HIER_Z11,
		data_buf[17],
		data_buf[16] }),
	.year_34({ data_buf[31],
		data_buf[30],
		data_buf[29],
		data_buf[28],
		data_buf[27],
		data_buf[26],
		data_buf[25],
		data_buf[24] }),
	.weekday({ UNCONNECTED18,
		UNCONNECTED17,
		UNCONNECTED16,
		UNCONNECTED15,
		UNCONNECTED14,
		dout[2],
		dout[1],
		dout[0] }));
   DLHQHDX0 done_reading_reg (.D(p_state[1]),
	.G(n_9),
	.Q(done_reading));
   DLLQHDX0 \data_buf_reg[6]  (.D(din[6]),
	.GN(n_8),
	.Q(data_buf[6]));
   DLLQHDX0 \data_buf_reg[2]  (.D(din[2]),
	.GN(n_8),
	.Q(data_buf[2]));
   DLLQHDX0 \data_buf_reg[10]  (.D(din[10]),
	.GN(n_8),
	.Q(data_buf[10]));
   DLLQHDX0 \data_buf_reg[9]  (.D(din[9]),
	.GN(n_8),
	.Q(data_buf[9]));
   DLLQHDX0 \data_buf_reg[1]  (.D(din[1]),
	.GN(n_8),
	.Q(data_buf[1]));
   DLLQHDX0 \data_buf_reg[8]  (.D(din[8]),
	.GN(n_8),
	.Q(data_buf[8]));
   DLLQHDX0 \data_buf_reg[17]  (.D(din[17]),
	.GN(n_8),
	.Q(data_buf[17]));
   DLLQHDX0 \data_buf_reg[5]  (.D(din[5]),
	.GN(n_8),
	.Q(data_buf[5]));
   DLLQHDX0 \data_buf_reg[0]  (.D(din[0]),
	.GN(n_8),
	.Q(data_buf[0]));
   DLLQHDX0 \data_buf_reg[16]  (.D(din[16]),
	.GN(n_8),
	.Q(data_buf[16]));
   DLLQHDX0 \data_buf_reg[31]  (.D(din[31]),
	.GN(n_8),
	.Q(data_buf[31]));
   DLLQHDX0 \data_buf_reg[15]  (.D(din[15]),
	.GN(n_8),
	.Q(data_buf[15]));
   DLLQHDX0 \data_buf_reg[30]  (.D(din[30]),
	.GN(n_8),
	.Q(data_buf[30]));
   DLLQHDX0 \data_buf_reg[7]  (.D(din[7]),
	.GN(n_8),
	.Q(data_buf[7]));
   DLLQHDX0 \data_buf_reg[4]  (.D(din[4]),
	.GN(n_8),
	.Q(data_buf[4]));
   DLLQHDX0 \data_buf_reg[14]  (.D(din[14]),
	.GN(n_8),
	.Q(data_buf[14]));
   DLLQHDX0 \data_buf_reg[28]  (.D(din[28]),
	.GN(n_8),
	.Q(data_buf[28]));
   DLLQHDX0 \data_buf_reg[27]  (.D(din[27]),
	.GN(n_8),
	.Q(data_buf[27]));
   DLLQHDX0 \data_buf_reg[13]  (.D(din[13]),
	.GN(n_8),
	.Q(data_buf[13]));
   DLLQHDX0 \data_buf_reg[26]  (.D(din[26]),
	.GN(n_8),
	.Q(data_buf[26]));
   DLLQHDX0 \data_buf_reg[25]  (.D(din[25]),
	.GN(n_8),
	.Q(data_buf[25]));
   DLLQHDX0 \data_buf_reg[3]  (.D(din[3]),
	.GN(n_8),
	.Q(data_buf[3]));
   DLLQHDX0 \data_buf_reg[12]  (.D(din[12]),
	.GN(n_8),
	.Q(data_buf[12]));
   DLLQHDX0 \data_buf_reg[24]  (.D(din[24]),
	.GN(n_8),
	.Q(data_buf[24]));
   DLLQHDX0 \data_buf_reg[11]  (.D(din[11]),
	.GN(n_8),
	.Q(data_buf[11]));
   DLLQHDX0 \data_buf_reg[29]  (.D(din[29]),
	.GN(n_8),
	.Q(data_buf[29]));
   ON21HDX0 g183__5115 (.A(n_11),
	.B(p_state[2]),
	.C(n_10),
	.Q(n_9));
   DLLQHDX0 write_result_reg (.D(p_state[2]),
	.GN(n_11),
	.Q(write_result));
   NA2HDX0 g185__7482 (.A(n_6),
	.B(p_state[1]),
	.Q(n_10));
   NA2I1HDX0 g186__4733 (.AN(p_state[1]),
	.B(n_6),
	.Q(n_8));
   OR2HDX0 g187__6161 (.A(p_state[1]),
	.B(p_state[0]),
	.Q(n_11));
   NO2I1HDX0 g188__9315 (.AN(p_state[0]),
	.B(p_state[2]),
	.Q(n_6));
   DFRRQHDX0 \p_state_reg[0]  (.C(clk),
	.D(n_4),
	.Q(p_state[0]),
	.RN(rst_n));
   DFRRQHDX0 \p_state_reg[1]  (.C(clk),
	.D(n_5),
	.Q(p_state[1]),
	.RN(rst_n));
   DFRRQHDX0 \p_state_reg[2]  (.C(FE_OFN1_clk),
	.D(n_1),
	.Q(p_state[2]),
	.RN(rst_n));
   NA2I1HDX0 g179__9945 (.AN(n_2),
	.B(n_8),
	.Q(n_5));
   ON21HDX0 g180__2883 (.A(n_11),
	.B(n_0),
	.C(n_3),
	.Q(n_4));
   INHDX0 g181 (.A(n_2),
	.Q(n_3));
   ON22HDX0 g182__2346 (.A(n_9),
	.B(n_11),
	.C(n_10),
	.D(n_0),
	.Q(n_2));
   NO3I1HDX0 g189__1666 (.AN(p_state[1]),
	.B(n_9),
	.C(p_state[2]),
	.Q(n_1));
   INHDX0 g184 (.A(juanito_data_available),
	.Q(n_0));
endmodule

module juanito (
	rst_n, 
	clk, 
	uart_data_valid, 
	din, 
	read_enable, 
	funky_read, 
	juanito_data_available, 
	data);
   input rst_n;
   input clk;
   input uart_data_valid;
   input [7:0] din;
   output read_enable;
   input funky_read;
   output juanito_data_available;
   output [31:0] data;

   // Internal wires
   wire [31:0] juanito_buffer;
   wire [1:0] cnt;
   wire [2:0] p_state;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;

   INHDX0 g884 (.A(n_62),
	.Q(n_56));
   DLLQHDX0 \data_reg[31]  (.D(n_36),
	.GN(n_63),
	.Q(data[31]));
   DLLQHDX0 \data_reg[30]  (.D(n_37),
	.GN(n_63),
	.Q(data[30]));
   DLLQHDX0 \data_reg[26]  (.D(n_42),
	.GN(n_63),
	.Q(data[26]));
   DLLQHDX0 \data_reg[12]  (.D(n_50),
	.GN(n_63),
	.Q(data[12]));
   DLLQHDX0 \data_reg[11]  (.D(n_51),
	.GN(n_63),
	.Q(data[11]));
   DLLQHDX0 \data_reg[25]  (.D(n_43),
	.GN(n_63),
	.Q(data[25]));
   DLLQHDX0 \data_reg[10]  (.D(n_52),
	.GN(n_63),
	.Q(data[10]));
   DLLQHDX0 \data_reg[9]  (.D(n_53),
	.GN(n_63),
	.Q(data[9]));
   DLLQHDX0 \data_reg[29]  (.D(n_38),
	.GN(n_63),
	.Q(data[29]));
   DLLQHDX0 \data_reg[24]  (.D(n_44),
	.GN(n_63),
	.Q(data[24]));
   DLLQHDX0 \data_reg[8]  (.D(n_54),
	.GN(n_63),
	.Q(data[8]));
   DLLQHDX0 \data_reg[7]  (.D(n_55),
	.GN(n_63),
	.Q(data[7]));
   DLLQHDX0 \data_reg[17]  (.D(n_45),
	.GN(n_63),
	.Q(data[17]));
   DLLQHDX0 \data_reg[6]  (.D(n_30),
	.GN(n_63),
	.Q(data[6]));
   DLLQHDX0 \data_reg[5]  (.D(n_31),
	.GN(n_63),
	.Q(data[5]));
   DLLQHDX0 \data_reg[28]  (.D(n_40),
	.GN(n_63),
	.Q(data[28]));
   DLLQHDX0 \data_reg[16]  (.D(n_46),
	.GN(n_63),
	.Q(data[16]));
   DLLQHDX0 \data_reg[4]  (.D(n_32),
	.GN(n_63),
	.Q(data[4]));
   DLLQHDX0 \data_reg[3]  (.D(n_33),
	.GN(n_63),
	.Q(data[3]));
   DLLQHDX0 \data_reg[15]  (.D(n_47),
	.GN(n_63),
	.Q(data[15]));
   DLLQHDX0 \data_reg[2]  (.D(n_34),
	.GN(n_63),
	.Q(data[2]));
   DLLQHDX0 \data_reg[1]  (.D(n_35),
	.GN(n_63),
	.Q(data[1]));
   DLLQHDX0 \data_reg[27]  (.D(n_41),
	.GN(n_63),
	.Q(data[27]));
   DLLQHDX0 \data_reg[14]  (.D(n_48),
	.GN(n_63),
	.Q(data[14]));
   DLLQHDX0 \data_reg[0]  (.D(n_39),
	.GN(n_63),
	.Q(data[0]));
   DLLQHDX0 \data_reg[13]  (.D(n_49),
	.GN(n_63),
	.Q(data[13]));
   NO2I1HDX0 g1247__7410 (.AN(juanito_buffer[7]),
	.B(n_60),
	.Q(n_55));
   NO2I1HDX0 g1248__6417 (.AN(juanito_buffer[8]),
	.B(n_60),
	.Q(n_54));
   NO2I1HDX0 g1249__5477 (.AN(juanito_buffer[9]),
	.B(n_60),
	.Q(n_53));
   NO2I1HDX0 g1250__2398 (.AN(juanito_buffer[10]),
	.B(n_60),
	.Q(n_52));
   NO2I1HDX0 g1251__5107 (.AN(juanito_buffer[11]),
	.B(n_60),
	.Q(n_51));
   NO2I1HDX0 g1252__6260 (.AN(juanito_buffer[12]),
	.B(n_60),
	.Q(n_50));
   NO2I1HDX0 g1253__4319 (.AN(juanito_buffer[13]),
	.B(n_60),
	.Q(n_49));
   NO2I1HDX0 g1254__8428 (.AN(juanito_buffer[14]),
	.B(n_60),
	.Q(n_48));
   NO2I1HDX0 g1255__5526 (.AN(juanito_buffer[15]),
	.B(n_60),
	.Q(n_47));
   NO2I1HDX0 g1256__6783 (.AN(juanito_buffer[16]),
	.B(n_60),
	.Q(n_46));
   NO2I1HDX0 g1257__3680 (.AN(juanito_buffer[17]),
	.B(n_60),
	.Q(n_45));
   NO2I1HDX0 g1258__1617 (.AN(juanito_buffer[24]),
	.B(n_60),
	.Q(n_44));
   NO2I1HDX0 g1259__2802 (.AN(juanito_buffer[25]),
	.B(n_60),
	.Q(n_43));
   NO2I1HDX0 g1260__1705 (.AN(juanito_buffer[26]),
	.B(n_60),
	.Q(n_42));
   NO2I1HDX0 g1261__5122 (.AN(juanito_buffer[27]),
	.B(n_60),
	.Q(n_41));
   NO2I1HDX0 g1262__8246 (.AN(juanito_buffer[28]),
	.B(n_60),
	.Q(n_40));
   NO2I1HDX0 g1263__7098 (.AN(juanito_buffer[0]),
	.B(n_60),
	.Q(n_39));
   NO2I1HDX0 g1264__6131 (.AN(juanito_buffer[29]),
	.B(n_60),
	.Q(n_38));
   NO2I1HDX0 g1265__1881 (.AN(juanito_buffer[30]),
	.B(n_60),
	.Q(n_37));
   NO2I1HDX0 g1266__5115 (.AN(juanito_buffer[31]),
	.B(n_60),
	.Q(n_36));
   NO2I1HDX0 g1267__7482 (.AN(juanito_buffer[1]),
	.B(n_60),
	.Q(n_35));
   NO2I1HDX0 g1268__4733 (.AN(juanito_buffer[2]),
	.B(n_60),
	.Q(n_34));
   NO2I1HDX0 g1269__6161 (.AN(juanito_buffer[3]),
	.B(n_60),
	.Q(n_33));
   NO2I1HDX0 g1270__9315 (.AN(juanito_buffer[4]),
	.B(n_60),
	.Q(n_32));
   NO2I1HDX0 g1271__9945 (.AN(juanito_buffer[5]),
	.B(n_60),
	.Q(n_31));
   NO2I1HDX0 g1272__2883 (.AN(juanito_buffer[6]),
	.B(n_60),
	.Q(n_30));
   DLHQHDX0 \juanito_buffer_reg[7]  (.D(n_23),
	.G(n_29),
	.Q(juanito_buffer[7]));
   DLHQHDX0 \juanito_buffer_reg[0]  (.D(n_18),
	.G(n_29),
	.Q(juanito_buffer[0]));
   DLHQHDX0 \juanito_buffer_reg[1]  (.D(n_21),
	.G(n_29),
	.Q(juanito_buffer[1]));
   DLHQHDX0 \juanito_buffer_reg[2]  (.D(n_19),
	.G(n_29),
	.Q(juanito_buffer[2]));
   DLHQHDX0 \juanito_buffer_reg[3]  (.D(n_20),
	.G(n_29),
	.Q(juanito_buffer[3]));
   DLHQHDX0 \juanito_buffer_reg[4]  (.D(n_24),
	.G(n_29),
	.Q(juanito_buffer[4]));
   DLHQHDX0 \juanito_buffer_reg[5]  (.D(n_25),
	.G(n_29),
	.Q(juanito_buffer[5]));
   DLHQHDX0 \juanito_buffer_reg[6]  (.D(n_22),
	.G(n_29),
	.Q(juanito_buffer[6]));
   DLHQHDX0 \juanito_buffer_reg[28]  (.D(n_24),
	.G(n_28),
	.Q(juanito_buffer[28]));
   DLHQHDX0 \juanito_buffer_reg[24]  (.D(n_18),
	.G(n_28),
	.Q(juanito_buffer[24]));
   DLHQHDX0 \juanito_buffer_reg[25]  (.D(n_21),
	.G(n_28),
	.Q(juanito_buffer[25]));
   DLHQHDX0 \juanito_buffer_reg[26]  (.D(n_19),
	.G(n_28),
	.Q(juanito_buffer[26]));
   DLHQHDX0 \juanito_buffer_reg[27]  (.D(n_20),
	.G(n_28),
	.Q(juanito_buffer[27]));
   DLHQHDX0 \juanito_buffer_reg[29]  (.D(n_25),
	.G(n_28),
	.Q(juanito_buffer[29]));
   DLHQHDX0 \juanito_buffer_reg[30]  (.D(n_22),
	.G(n_28),
	.Q(juanito_buffer[30]));
   DLHQHDX0 \juanito_buffer_reg[31]  (.D(n_23),
	.G(n_28),
	.Q(juanito_buffer[31]));
   DLLQHDX0 \juanito_buffer_reg[8]  (.D(n_18),
	.GN(n_27),
	.Q(juanito_buffer[8]));
   DLLQHDX0 \juanito_buffer_reg[9]  (.D(n_21),
	.GN(n_27),
	.Q(juanito_buffer[9]));
   DLLQHDX0 \juanito_buffer_reg[10]  (.D(n_19),
	.GN(n_27),
	.Q(juanito_buffer[10]));
   DLLQHDX0 \juanito_buffer_reg[11]  (.D(n_20),
	.GN(n_27),
	.Q(juanito_buffer[11]));
   DLLQHDX0 \juanito_buffer_reg[12]  (.D(n_24),
	.GN(n_27),
	.Q(juanito_buffer[12]));
   DLLQHDX0 \juanito_buffer_reg[13]  (.D(n_25),
	.GN(n_27),
	.Q(juanito_buffer[13]));
   DLLQHDX0 \juanito_buffer_reg[14]  (.D(n_22),
	.GN(n_27),
	.Q(juanito_buffer[14]));
   DLLQHDX0 \juanito_buffer_reg[15]  (.D(n_23),
	.GN(n_27),
	.Q(juanito_buffer[15]));
   DLLQHDX0 \juanito_buffer_reg[16]  (.D(n_18),
	.GN(n_26),
	.Q(juanito_buffer[16]));
   DLLQHDX0 \juanito_buffer_reg[17]  (.D(n_21),
	.GN(n_26),
	.Q(juanito_buffer[17]));
   DLLQHDX0 juanito_data_available_reg (.D(n_16),
	.GN(n_63),
	.Q(juanito_data_available));
   DLLQHDX0 read_enable_reg (.D(n_17),
	.GN(n_15),
	.Q(read_enable));
   NO2I1HDX0 g1301__2346 (.AN(din[5]),
	.B(n_59),
	.Q(n_25));
   NO2I1HDX0 g1302__1666 (.AN(din[4]),
	.B(n_59),
	.Q(n_24));
   NO2I1HDX0 g1303__7410 (.AN(din[7]),
	.B(n_59),
	.Q(n_23));
   NO2I1HDX0 g1304__6417 (.AN(din[6]),
	.B(n_59),
	.Q(n_22));
   NO2I1HDX0 g1305__5477 (.AN(din[1]),
	.B(n_59),
	.Q(n_21));
   NO2I1HDX0 g1306__2398 (.AN(n_62),
	.B(n_13),
	.Q(n_26));
   NO2I1HDX0 g1307__5107 (.AN(din[3]),
	.B(n_59),
	.Q(n_20));
   NO2I1HDX0 g1308__6260 (.AN(din[2]),
	.B(n_59),
	.Q(n_19));
   NO2I1HDX0 g1309__4319 (.AN(din[0]),
	.B(n_59),
	.Q(n_18));
   ON21HDX0 g1310__8428 (.A(n_12),
	.B(n_61),
	.C(n_62),
	.Q(n_28));
   ON31HDX0 g1311__5526 (.A(cnt[1]),
	.B(cnt[0]),
	.C(n_12),
	.D(n_62),
	.Q(n_29));
   NO2I1HDX0 g1312__6783 (.AN(n_62),
	.B(n_14),
	.Q(n_27));
   INHDX0 g1313 (.A(n_59),
	.Q(n_17));
   INHDX0 g1314 (.A(n_60),
	.Q(n_16));
   OR2HDX0 g1315__3680 (.A(n_63),
	.B(p_state[2]),
	.Q(n_62));
   NA2I1HDX0 g1316__1617 (.AN(n_12),
	.B(p_state[0]),
	.Q(n_59));
   NA2I1HDX0 g1317__2802 (.AN(n_63),
	.B(p_state[2]),
	.Q(n_60));
   AND2HDX0 g1318__1705 (.A(n_63),
	.B(n_58),
	.Q(n_15));
   NO3I1HDX0 g1319__5122 (.AN(cnt[0]),
	.B(n_12),
	.C(cnt[1]),
	.Q(n_14));
   NO3I1HDX0 g1320__8246 (.AN(cnt[1]),
	.B(n_12),
	.C(cnt[0]),
	.Q(n_13));
   NA2HDX0 g1321__7098 (.A(cnt[1]),
	.B(cnt[0]),
	.Q(n_61));
   NA2I1HDX0 g1322__6131 (.AN(p_state[2]),
	.B(p_state[0]),
	.Q(n_58));
   OR2HDX0 g1323__1881 (.A(p_state[2]),
	.B(p_state[1]),
	.Q(n_12));
   OR2HDX0 g1324__5115 (.A(p_state[0]),
	.B(p_state[1]),
	.Q(n_63));
   DFRRQHDX0 \p_state_reg[1]  (.C(clk),
	.D(n_11),
	.Q(p_state[1]),
	.RN(rst_n));
   DFRRQHDX0 \p_state_reg[2]  (.C(clk),
	.D(n_10),
	.Q(p_state[2]),
	.RN(rst_n));
   DFRRQHDX0 \p_state_reg[0]  (.C(clk),
	.D(n_9),
	.Q(p_state[0]),
	.RN(rst_n));
   AO211HDX0 g1022__7482 (.A(n_3),
	.B(uart_data_valid),
	.C(n_5),
	.D(n_2),
	.Q(n_11));
   ON32HDX0 g1023__4733 (.A(uart_data_valid),
	.B(n_61),
	.C(n_4),
	.D(funky_read),
	.E(n_60),
	.Q(n_10));
   DLHQHDX0 \cnt_reg[1]  (.D(n_6),
	.G(n_8),
	.Q(cnt[1]));
   AO221HDX0 g1025__6161 (.A(p_state[0]),
	.B(n_0),
	.C(uart_data_valid),
	.D(n_56),
	.E(n_5),
	.Q(n_9));
   DLHQHDX0 \cnt_reg[0]  (.D(n_7),
	.G(n_8),
	.Q(cnt[0]));
   NO2HDX0 g1027__9315 (.A(n_4),
	.B(cnt[0]),
	.Q(n_7));
   NO2HDX0 g1028__9945 (.A(n_4),
	.B(n_1),
	.Q(n_6));
   ON31HDX0 g1029__2883 (.A(uart_data_valid),
	.B(p_state[0]),
	.C(p_state[2]),
	.D(n_63),
	.Q(n_8));
   NO3I2HDX0 g1030__2346 (.AN(n_0),
	.BN(n_61),
	.C(uart_data_valid),
	.Q(n_5));
   INHDX0 g1031 (.A(n_4),
	.Q(n_3));
   NA2I1HDX0 g1032__1666 (.AN(p_state[0]),
	.B(n_0),
	.Q(n_4));
   ON21HDX0 g1033__7410 (.A(n_58),
	.B(uart_data_valid),
	.C(n_59),
	.Q(n_2));
   EN2HDX0 g1034__6417 (.A(cnt[0]),
	.B(cnt[1]),
	.Q(n_1));
   NO2I1HDX0 g1035__5477 (.AN(p_state[1]),
	.B(p_state[2]),
	.Q(n_0));
endmodule

module simpleuart (
	clk, 
	resetn, 
	ser_tx, 
	ser_rx, 
	reg_div_we, 
	reg_dat_we, 
	reg_dat_re, 
	reg_dat_di, 
	reg_dat_do, 
	reg_dat_wait, 
	buf_valid, 
	FE_OFN0_clk);
   input clk;
   input resetn;
   output ser_tx;
   input ser_rx;
   input [3:0] reg_div_we;
   input reg_dat_we;
   input reg_dat_re;
   input [31:0] reg_dat_di;
   output [31:0] reg_dat_do;
   output reg_dat_wait;
   output buf_valid;
   input FE_OFN0_clk;

   // Internal wires
   wire [7:0] recv_buf_data;
   wire [31:0] recv_divcnt;
   wire [7:0] recv_pattern;
   wire [3:0] recv_state;
   wire [3:0] send_bitcnt;
   wire [31:0] send_divcnt;
   wire [9:0] send_pattern;
   wire inc_add_80_31_n_0;
   wire inc_add_80_31_n_2;
   wire inc_add_80_31_n_4;
   wire inc_add_80_31_n_6;
   wire inc_add_80_31_n_8;
   wire inc_add_80_31_n_10;
   wire inc_add_80_31_n_12;
   wire inc_add_80_31_n_14;
   wire inc_add_80_31_n_16;
   wire inc_add_80_31_n_18;
   wire inc_add_80_31_n_20;
   wire inc_add_80_31_n_22;
   wire inc_add_80_31_n_24;
   wire inc_add_80_31_n_26;
   wire inc_add_80_31_n_28;
   wire inc_add_80_31_n_30;
   wire inc_add_80_31_n_32;
   wire inc_add_80_31_n_34;
   wire inc_add_80_31_n_36;
   wire inc_add_80_31_n_38;
   wire inc_add_80_31_n_40;
   wire inc_add_80_31_n_42;
   wire inc_add_80_31_n_44;
   wire inc_add_80_31_n_46;
   wire inc_add_80_31_n_48;
   wire inc_add_80_31_n_50;
   wire inc_add_80_31_n_52;
   wire inc_add_80_31_n_54;
   wire inc_add_80_31_n_56;
   wire inc_add_80_31_n_58;
   wire inc_add_118_30_n_0;
   wire inc_add_118_30_n_2;
   wire inc_add_118_30_n_4;
   wire inc_add_118_30_n_6;
   wire inc_add_118_30_n_8;
   wire inc_add_118_30_n_10;
   wire inc_add_118_30_n_12;
   wire inc_add_118_30_n_14;
   wire inc_add_118_30_n_16;
   wire inc_add_118_30_n_18;
   wire inc_add_118_30_n_20;
   wire inc_add_118_30_n_22;
   wire inc_add_118_30_n_24;
   wire inc_add_118_30_n_26;
   wire inc_add_118_30_n_28;
   wire inc_add_118_30_n_30;
   wire inc_add_118_30_n_32;
   wire inc_add_118_30_n_34;
   wire inc_add_118_30_n_36;
   wire inc_add_118_30_n_38;
   wire inc_add_118_30_n_40;
   wire inc_add_118_30_n_42;
   wire inc_add_118_30_n_44;
   wire inc_add_118_30_n_46;
   wire inc_add_118_30_n_48;
   wire inc_add_118_30_n_50;
   wire inc_add_118_30_n_52;
   wire inc_add_118_30_n_54;
   wire inc_add_118_30_n_56;
   wire inc_add_118_30_n_58;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;
   wire n_193;
   wire n_194;
   wire n_195;
   wire n_196;
   wire n_197;
   wire n_198;
   wire n_199;
   wire n_200;
   wire n_201;
   wire n_202;
   wire n_203;
   wire n_204;
   wire n_205;
   wire n_206;
   wire n_207;
   wire n_208;
   wire n_209;
   wire n_210;
   wire n_211;
   wire n_212;
   wire n_213;
   wire n_214;
   wire n_215;
   wire n_216;
   wire n_217;
   wire n_218;
   wire n_219;
   wire n_220;
   wire n_221;
   wire n_222;
   wire n_223;
   wire n_224;
   wire n_225;
   wire n_226;
   wire n_227;
   wire n_228;
   wire n_229;
   wire n_230;
   wire n_231;
   wire n_232;
   wire n_233;
   wire send_dummy;

   NA2I1HDX0 g3257__2398 (.AN(recv_buf_data[4]),
	.B(buf_valid),
	.Q(reg_dat_do[4]));
   NA2I1HDX0 g3258__5107 (.AN(recv_buf_data[6]),
	.B(buf_valid),
	.Q(reg_dat_do[6]));
   NA2I1HDX0 g3259__6260 (.AN(recv_buf_data[7]),
	.B(buf_valid),
	.Q(reg_dat_do[7]));
   NA2I1HDX0 g3260__4319 (.AN(recv_buf_data[0]),
	.B(buf_valid),
	.Q(reg_dat_do[0]));
   NA2I1HDX0 g3261__8428 (.AN(recv_buf_data[2]),
	.B(buf_valid),
	.Q(reg_dat_do[2]));
   NA2I1HDX0 g3262__5526 (.AN(recv_buf_data[5]),
	.B(buf_valid),
	.Q(reg_dat_do[5]));
   NA2I1HDX0 g3263__6783 (.AN(recv_buf_data[3]),
	.B(buf_valid),
	.Q(reg_dat_do[3]));
   NA2I1HDX0 g3264__3680 (.AN(recv_buf_data[1]),
	.B(buf_valid),
	.Q(reg_dat_do[1]));
   DFRQHDX0 \recv_buf_data_reg[0]  (.C(clk),
	.D(n_116),
	.Q(recv_buf_data[0]));
   DFRQHDX0 \recv_buf_data_reg[1]  (.C(clk),
	.D(n_117),
	.Q(recv_buf_data[1]));
   DFRQHDX0 \recv_buf_data_reg[2]  (.C(clk),
	.D(n_107),
	.Q(recv_buf_data[2]));
   DFRQHDX0 \recv_buf_data_reg[3]  (.C(clk),
	.D(n_112),
	.Q(recv_buf_data[3]));
   DFRQHDX0 \recv_buf_data_reg[4]  (.C(clk),
	.D(n_111),
	.Q(recv_buf_data[4]));
   DFRQHDX0 \recv_buf_data_reg[5]  (.C(clk),
	.D(n_110),
	.Q(recv_buf_data[5]));
   DFRQHDX0 \recv_buf_data_reg[6]  (.C(clk),
	.D(n_109),
	.Q(recv_buf_data[6]));
   DFRQHDX0 \recv_buf_data_reg[7]  (.C(clk),
	.D(n_108),
	.Q(recv_buf_data[7]));
   DFRQHDX0 \recv_divcnt_reg[0]  (.C(clk),
	.D(n_133),
	.Q(recv_divcnt[0]));
   DFRQHDX0 \recv_divcnt_reg[1]  (.C(clk),
	.D(n_144),
	.Q(recv_divcnt[1]));
   DFRQHDX0 \recv_divcnt_reg[2]  (.C(clk),
	.D(n_131),
	.Q(recv_divcnt[2]));
   DFRQHDX0 \recv_divcnt_reg[3]  (.C(clk),
	.D(n_130),
	.Q(recv_divcnt[3]));
   DFRQHDX0 \recv_divcnt_reg[4]  (.C(clk),
	.D(n_129),
	.Q(recv_divcnt[4]));
   DFRQHDX0 \recv_divcnt_reg[5]  (.C(clk),
	.D(n_128),
	.Q(recv_divcnt[5]));
   DFRQHDX0 \recv_divcnt_reg[6]  (.C(clk),
	.D(n_127),
	.Q(recv_divcnt[6]));
   DFRQHDX0 \recv_divcnt_reg[7]  (.C(clk),
	.D(n_152),
	.Q(recv_divcnt[7]));
   DFRQHDX0 \recv_divcnt_reg[8]  (.C(FE_OFN0_clk),
	.D(n_151),
	.Q(recv_divcnt[8]));
   DFRQHDX0 \recv_divcnt_reg[9]  (.C(FE_OFN0_clk),
	.D(n_150),
	.Q(recv_divcnt[9]));
   DFRQHDX0 \recv_divcnt_reg[10]  (.C(FE_OFN0_clk),
	.D(n_161),
	.Q(recv_divcnt[10]));
   DFRQHDX0 \recv_divcnt_reg[11]  (.C(FE_OFN0_clk),
	.D(n_148),
	.Q(recv_divcnt[11]));
   DFRQHDX0 \recv_divcnt_reg[12]  (.C(FE_OFN0_clk),
	.D(n_147),
	.Q(recv_divcnt[12]));
   DFRQHDX0 \recv_divcnt_reg[13]  (.C(FE_OFN0_clk),
	.D(n_146),
	.Q(recv_divcnt[13]));
   DFRQHDX0 \recv_divcnt_reg[14]  (.C(FE_OFN0_clk),
	.D(n_149),
	.Q(recv_divcnt[14]));
   DFRQHDX0 \recv_divcnt_reg[15]  (.C(FE_OFN0_clk),
	.D(n_153),
	.Q(recv_divcnt[15]));
   DFRQHDX0 \recv_divcnt_reg[16]  (.C(FE_OFN0_clk),
	.D(n_154),
	.Q(recv_divcnt[16]));
   DFRQHDX0 \recv_divcnt_reg[17]  (.C(FE_OFN0_clk),
	.D(n_155),
	.Q(recv_divcnt[17]));
   DFRQHDX0 \recv_divcnt_reg[18]  (.C(FE_OFN0_clk),
	.D(n_156),
	.Q(recv_divcnt[18]));
   DFRQHDX0 \recv_divcnt_reg[19]  (.C(FE_OFN0_clk),
	.D(n_157),
	.Q(recv_divcnt[19]));
   DFRQHDX0 \recv_divcnt_reg[20]  (.C(FE_OFN0_clk),
	.D(n_158),
	.Q(recv_divcnt[20]));
   DFRQHDX0 \recv_divcnt_reg[21]  (.C(FE_OFN0_clk),
	.D(n_159),
	.Q(recv_divcnt[21]));
   DFRQHDX0 \recv_divcnt_reg[22]  (.C(FE_OFN0_clk),
	.D(n_160),
	.Q(recv_divcnt[22]));
   DFRQHDX0 \recv_divcnt_reg[23]  (.C(FE_OFN0_clk),
	.D(n_142),
	.Q(recv_divcnt[23]));
   DFRQHDX0 \recv_divcnt_reg[24]  (.C(FE_OFN0_clk),
	.D(n_132),
	.Q(recv_divcnt[24]));
   DFRQHDX0 \recv_divcnt_reg[25]  (.C(FE_OFN0_clk),
	.D(n_143),
	.Q(recv_divcnt[25]));
   DFRQHDX0 \recv_divcnt_reg[26]  (.C(clk),
	.D(n_141),
	.Q(recv_divcnt[26]));
   DFRQHDX0 \recv_divcnt_reg[27]  (.C(clk),
	.D(n_140),
	.Q(recv_divcnt[27]));
   DFRQHDX0 \recv_divcnt_reg[28]  (.C(FE_OFN0_clk),
	.D(n_139),
	.Q(recv_divcnt[28]));
   DFRQHDX0 \recv_divcnt_reg[29]  (.C(FE_OFN0_clk),
	.D(n_138),
	.Q(recv_divcnt[29]));
   DFRQHDX0 \recv_divcnt_reg[30]  (.C(FE_OFN0_clk),
	.D(n_137),
	.Q(recv_divcnt[30]));
   DFRQHDX0 \recv_divcnt_reg[31]  (.C(clk),
	.D(n_136),
	.Q(recv_divcnt[31]));
   DFRQHDX0 \recv_pattern_reg[0]  (.C(clk),
	.D(n_126),
	.Q(recv_pattern[0]));
   DFRQHDX0 \recv_pattern_reg[1]  (.C(clk),
	.D(n_125),
	.Q(recv_pattern[1]));
   DFRQHDX0 \recv_pattern_reg[2]  (.C(clk),
	.D(n_124),
	.Q(recv_pattern[2]));
   DFRQHDX0 \recv_pattern_reg[3]  (.C(clk),
	.D(n_121),
	.Q(recv_pattern[3]));
   DFRQHDX0 \recv_pattern_reg[4]  (.C(clk),
	.D(n_123),
	.Q(recv_pattern[4]));
   DFRQHDX0 \recv_pattern_reg[5]  (.C(clk),
	.D(n_122),
	.Q(recv_pattern[5]));
   DFRQHDX0 \recv_pattern_reg[6]  (.C(clk),
	.D(n_134),
	.Q(recv_pattern[6]));
   DFRQHDX0 \recv_pattern_reg[7]  (.C(clk),
	.D(n_135),
	.Q(recv_pattern[7]));
   DFRQHDX0 \recv_state_reg[2]  (.C(clk),
	.D(n_167),
	.Q(recv_state[2]));
   DFRQHDX0 \recv_state_reg[3]  (.C(clk),
	.D(n_169),
	.Q(recv_state[3]));
   DFRQHDX0 \send_bitcnt_reg[0]  (.C(FE_OFN0_clk),
	.D(n_91),
	.Q(send_bitcnt[0]));
   DFRQHDX0 \send_bitcnt_reg[1]  (.C(FE_OFN0_clk),
	.D(n_0),
	.Q(send_bitcnt[1]));
   DFRQHDX0 \send_bitcnt_reg[2]  (.C(FE_OFN0_clk),
	.D(n_85),
	.Q(send_bitcnt[2]));
   DFRQHDX0 \send_bitcnt_reg[3]  (.C(FE_OFN0_clk),
	.D(n_96),
	.Q(send_bitcnt[3]));
   DFRQHDX0 \send_divcnt_reg[0]  (.C(FE_OFN0_clk),
	.D(n_63),
	.Q(send_divcnt[0]));
   DFRQHDX0 \send_divcnt_reg[1]  (.C(FE_OFN0_clk),
	.D(n_65),
	.Q(send_divcnt[1]));
   DFRQHDX0 \send_divcnt_reg[2]  (.C(FE_OFN0_clk),
	.D(n_70),
	.Q(send_divcnt[2]));
   DFRQHDX0 \send_divcnt_reg[3]  (.C(FE_OFN0_clk),
	.D(n_62),
	.Q(send_divcnt[3]));
   DFRQHDX0 \send_divcnt_reg[4]  (.C(FE_OFN0_clk),
	.D(n_68),
	.Q(send_divcnt[4]));
   DFRQHDX0 \send_divcnt_reg[5]  (.C(FE_OFN0_clk),
	.D(n_61),
	.Q(send_divcnt[5]));
   DFRQHDX0 \send_divcnt_reg[6]  (.C(FE_OFN0_clk),
	.D(n_72),
	.Q(send_divcnt[6]));
   DFRQHDX0 \send_divcnt_reg[7]  (.C(FE_OFN0_clk),
	.D(n_49),
	.Q(send_divcnt[7]));
   DFRQHDX0 \send_divcnt_reg[8]  (.C(FE_OFN0_clk),
	.D(n_57),
	.Q(send_divcnt[8]));
   DFRQHDX0 \send_divcnt_reg[9]  (.C(FE_OFN0_clk),
	.D(n_69),
	.Q(send_divcnt[9]));
   DFRQHDX0 \send_divcnt_reg[10]  (.C(FE_OFN0_clk),
	.D(n_67),
	.Q(send_divcnt[10]));
   DFRQHDX0 \send_divcnt_reg[11]  (.C(FE_OFN0_clk),
	.D(n_55),
	.Q(send_divcnt[11]));
   DFRQHDX0 \send_divcnt_reg[12]  (.C(FE_OFN0_clk),
	.D(n_54),
	.Q(send_divcnt[12]));
   DFRQHDX0 \send_divcnt_reg[13]  (.C(FE_OFN0_clk),
	.D(n_53),
	.Q(send_divcnt[13]));
   DFRQHDX0 \send_divcnt_reg[14]  (.C(FE_OFN0_clk),
	.D(n_43),
	.Q(send_divcnt[14]));
   DFRQHDX0 \send_divcnt_reg[15]  (.C(FE_OFN0_clk),
	.D(n_46),
	.Q(send_divcnt[15]));
   DFRQHDX0 \send_divcnt_reg[16]  (.C(FE_OFN0_clk),
	.D(n_66),
	.Q(send_divcnt[16]));
   DFRQHDX0 \send_divcnt_reg[17]  (.C(FE_OFN0_clk),
	.D(n_52),
	.Q(send_divcnt[17]));
   DFRQHDX0 \send_divcnt_reg[18]  (.C(FE_OFN0_clk),
	.D(n_71),
	.Q(send_divcnt[18]));
   DFRQHDX0 \send_divcnt_reg[19]  (.C(FE_OFN0_clk),
	.D(n_51),
	.Q(send_divcnt[19]));
   DFRQHDX0 \send_divcnt_reg[20]  (.C(FE_OFN0_clk),
	.D(n_73),
	.Q(send_divcnt[20]));
   DFRQHDX0 \send_divcnt_reg[21]  (.C(FE_OFN0_clk),
	.D(n_50),
	.Q(send_divcnt[21]));
   DFRQHDX0 \send_divcnt_reg[22]  (.C(FE_OFN0_clk),
	.D(n_74),
	.Q(send_divcnt[22]));
   DFRQHDX0 \send_divcnt_reg[23]  (.C(FE_OFN0_clk),
	.D(n_58),
	.Q(send_divcnt[23]));
   DFRQHDX0 \send_divcnt_reg[24]  (.C(FE_OFN0_clk),
	.D(n_75),
	.Q(send_divcnt[24]));
   DFRQHDX0 \send_divcnt_reg[25]  (.C(FE_OFN0_clk),
	.D(n_48),
	.Q(send_divcnt[25]));
   DFRQHDX0 \send_divcnt_reg[26]  (.C(FE_OFN0_clk),
	.D(n_76),
	.Q(send_divcnt[26]));
   DFRQHDX0 \send_divcnt_reg[27]  (.C(FE_OFN0_clk),
	.D(n_47),
	.Q(send_divcnt[27]));
   DFRQHDX0 \send_divcnt_reg[28]  (.C(FE_OFN0_clk),
	.D(n_77),
	.Q(send_divcnt[28]));
   DFRQHDX0 \send_divcnt_reg[29]  (.C(FE_OFN0_clk),
	.D(n_45),
	.Q(send_divcnt[29]));
   DFRQHDX0 \send_divcnt_reg[30]  (.C(FE_OFN0_clk),
	.D(n_56),
	.Q(send_divcnt[30]));
   DFRQHDX0 \send_divcnt_reg[31]  (.C(FE_OFN0_clk),
	.D(n_44),
	.Q(send_divcnt[31]));
   DFRQHDX0 send_dummy_reg (.C(FE_OFN0_clk),
	.D(n_30),
	.Q(send_dummy));
   DFRQHDX0 \send_pattern_reg[0]  (.C(FE_OFN0_clk),
	.D(n_86),
	.Q(ser_tx));
   DFRQHDX0 \send_pattern_reg[1]  (.C(FE_OFN0_clk),
	.D(n_92),
	.Q(send_pattern[1]));
   DFRQHDX0 \send_pattern_reg[2]  (.C(FE_OFN0_clk),
	.D(n_93),
	.Q(send_pattern[2]));
   DFRQHDX0 \send_pattern_reg[3]  (.C(FE_OFN0_clk),
	.D(n_94),
	.Q(send_pattern[3]));
   DFRQHDX0 \send_pattern_reg[4]  (.C(FE_OFN0_clk),
	.D(n_89),
	.Q(send_pattern[4]));
   DFRQHDX0 \send_pattern_reg[5]  (.C(FE_OFN0_clk),
	.D(n_90),
	.Q(send_pattern[5]));
   DFRQHDX0 \send_pattern_reg[6]  (.C(FE_OFN0_clk),
	.D(n_87),
	.Q(send_pattern[6]));
   DFRQHDX0 \send_pattern_reg[7]  (.C(FE_OFN0_clk),
	.D(n_88),
	.Q(send_pattern[7]));
   DFRQHDX0 \send_pattern_reg[8]  (.C(FE_OFN0_clk),
	.D(n_84),
	.Q(send_pattern[8]));
   ON31HDX0 g5512__1617 (.A(recv_state[3]),
	.B(n_15),
	.C(n_106),
	.D(n_166),
	.Q(n_169));
   ON321HDX0 g5514__2802 (.A(n_145),
	.B(n_4),
	.C(n_1),
	.D(n_2),
	.E(n_163),
	.F(n_115),
	.Q(n_168));
   AO22HDX0 g5515__1705 (.A(n_164),
	.B(recv_state[2]),
	.C(n_119),
	.D(n_5),
	.Q(n_167));
   NA2HDX0 g5516__5122 (.A(n_164),
	.B(recv_state[3]),
	.Q(n_166));
   ON22HDX0 g5517__8246 (.A(n_163),
	.B(n_1),
	.C(n_162),
	.D(recv_state[0]),
	.Q(n_165));
   NA2I1HDX0 g5518__7098 (.AN(n_119),
	.B(n_163),
	.Q(n_164));
   AN21HDX0 g5540__6131 (.A(n_120),
	.B(resetn),
	.C(n_105),
	.Q(n_162));
   NA2HDX0 g5557__1881 (.A(n_145),
	.B(n_103),
	.Q(n_163));
   NO2I1HDX0 g5561__5115 (.AN(n_174),
	.B(n_118),
	.Q(n_161));
   NO2I1HDX0 g5562__7482 (.AN(n_186),
	.B(n_118),
	.Q(n_160));
   NO2I1HDX0 g5563__4733 (.AN(n_185),
	.B(n_118),
	.Q(n_159));
   NO2I1HDX0 g5564__6161 (.AN(n_184),
	.B(n_118),
	.Q(n_158));
   NO2I1HDX0 g5565__9315 (.AN(n_183),
	.B(n_118),
	.Q(n_157));
   NO2I1HDX0 g5566__9945 (.AN(n_182),
	.B(n_118),
	.Q(n_156));
   NO2I1HDX0 g5567__2883 (.AN(n_181),
	.B(n_118),
	.Q(n_155));
   NO2I1HDX0 g5568__2346 (.AN(n_180),
	.B(n_118),
	.Q(n_154));
   NO2I1HDX0 g5569__1666 (.AN(n_179),
	.B(n_118),
	.Q(n_153));
   NO2I1HDX0 g5570__7410 (.AN(n_202),
	.B(n_118),
	.Q(n_152));
   NO2I1HDX0 g5571__6417 (.AN(n_172),
	.B(n_118),
	.Q(n_151));
   NO2I1HDX0 g5572__5477 (.AN(n_173),
	.B(n_118),
	.Q(n_150));
   NO2I1HDX0 g5573__2398 (.AN(n_178),
	.B(n_118),
	.Q(n_149));
   NO2I1HDX0 g5574__5107 (.AN(n_175),
	.B(n_118),
	.Q(n_148));
   NO2I1HDX0 g5575__6260 (.AN(n_176),
	.B(n_118),
	.Q(n_147));
   NO2I1HDX0 g5576__4319 (.AN(n_177),
	.B(n_118),
	.Q(n_146));
   NO2I1HDX0 g5586__8428 (.AN(n_196),
	.B(n_118),
	.Q(n_144));
   NO2I1HDX0 g5587__5526 (.AN(n_189),
	.B(n_118),
	.Q(n_143));
   NO2I1HDX0 g5588__6783 (.AN(n_187),
	.B(n_118),
	.Q(n_142));
   NO2I1HDX0 g5589__3680 (.AN(n_190),
	.B(n_118),
	.Q(n_141));
   NO2I1HDX0 g5590__1617 (.AN(n_191),
	.B(n_118),
	.Q(n_140));
   NO2I1HDX0 g5591__2802 (.AN(n_192),
	.B(n_118),
	.Q(n_139));
   NO2I1HDX0 g5592__1705 (.AN(n_193),
	.B(n_118),
	.Q(n_138));
   NO2I1HDX0 g5593__5122 (.AN(n_194),
	.B(n_118),
	.Q(n_137));
   NO2I1HDX0 g5594__8246 (.AN(n_195),
	.B(n_118),
	.Q(n_136));
   NO2HDX0 g5595__7098 (.A(n_113),
	.B(n_4),
	.Q(n_135));
   AO22HDX0 g5596__6131 (.A(n_105),
	.B(recv_pattern[7]),
	.C(n_103),
	.D(recv_pattern[6]),
	.Q(n_134));
   NO2HDX0 g5597__1881 (.A(n_118),
	.B(recv_divcnt[0]),
	.Q(n_133));
   NO2I1HDX0 g5598__5115 (.AN(n_188),
	.B(n_118),
	.Q(n_132));
   NO2I1HDX0 g5599__7482 (.AN(n_197),
	.B(n_118),
	.Q(n_131));
   NO2I1HDX0 g5600__4733 (.AN(n_198),
	.B(n_118),
	.Q(n_130));
   NO2I1HDX0 g5601__6161 (.AN(n_199),
	.B(n_118),
	.Q(n_129));
   NO2I1HDX0 g5602__9315 (.AN(n_200),
	.B(n_118),
	.Q(n_128));
   NO2I1HDX0 g5603__9945 (.AN(n_201),
	.B(n_118),
	.Q(n_127));
   AO22HDX0 g5604__2883 (.A(n_105),
	.B(recv_pattern[1]),
	.C(n_103),
	.D(recv_pattern[0]),
	.Q(n_126));
   AO22HDX0 g5605__2346 (.A(n_105),
	.B(recv_pattern[2]),
	.C(n_103),
	.D(recv_pattern[1]),
	.Q(n_125));
   AO22HDX0 g5606__1666 (.A(n_105),
	.B(recv_pattern[3]),
	.C(n_103),
	.D(recv_pattern[2]),
	.Q(n_124));
   AO22HDX0 g5607__7410 (.A(n_105),
	.B(recv_pattern[5]),
	.C(n_103),
	.D(recv_pattern[4]),
	.Q(n_123));
   AO22HDX0 g5608__6417 (.A(n_105),
	.B(recv_pattern[6]),
	.C(n_103),
	.D(recv_pattern[5]),
	.Q(n_122));
   AO22HDX0 g5609__5477 (.A(n_105),
	.B(recv_pattern[4]),
	.C(n_103),
	.D(recv_pattern[3]),
	.Q(n_121));
   NO2HDX0 g5610__2398 (.A(n_120),
	.B(n_95),
	.Q(n_145));
   AO22HDX0 g5611__5107 (.A(n_98),
	.B(recv_pattern[1]),
	.C(n_100),
	.D(recv_buf_data[1]),
	.Q(n_117));
   NO2HDX0 g5612__6260 (.A(n_102),
	.B(n_4),
	.Q(n_116));
   AO211HDX0 g5613__4319 (.A(n_1),
	.B(n_2),
	.C(n_5),
	.D(n_106),
	.Q(n_115));
   ON31HDX0 g5614__8428 (.A(reg_dat_re),
	.B(n_3),
	.C(n_99),
	.D(n_97),
	.Q(n_114));
   AN21HDX0 g5615__5526 (.A(n_1),
	.B(ser_rx),
	.C(n_104),
	.Q(n_120));
   NO2I1HDX0 g5616__6783 (.AN(n_15),
	.B(n_106),
	.Q(n_119));
   NA2HDX0 g5617__3680 (.A(n_103),
	.B(n_104),
	.Q(n_118));
   MU2IHDX0 g5618__1617 (.IN0(recv_pattern[7]),
	.IN1(ser_rx),
	.Q(n_113),
	.S(n_101));
   AO22HDX0 g5619__2802 (.A(n_98),
	.B(recv_pattern[3]),
	.C(n_100),
	.D(recv_buf_data[3]),
	.Q(n_112));
   AO22HDX0 g5620__1705 (.A(n_98),
	.B(recv_pattern[4]),
	.C(n_100),
	.D(recv_buf_data[4]),
	.Q(n_111));
   AO22HDX0 g5621__5122 (.A(n_98),
	.B(recv_pattern[5]),
	.C(n_100),
	.D(recv_buf_data[5]),
	.Q(n_110));
   AO22HDX0 g5622__8246 (.A(n_98),
	.B(recv_pattern[6]),
	.C(n_100),
	.D(recv_buf_data[6]),
	.Q(n_109));
   AO22HDX0 g5623__7098 (.A(n_98),
	.B(recv_pattern[7]),
	.C(n_100),
	.D(recv_buf_data[7]),
	.Q(n_108));
   AO22HDX0 g5624__6131 (.A(n_98),
	.B(recv_pattern[2]),
	.C(n_100),
	.D(recv_buf_data[2]),
	.Q(n_107));
   INHDX0 g5625 (.A(n_106),
	.Q(n_105));
   NA2HDX0 g5628__1881 (.A(n_101),
	.B(resetn),
	.Q(n_106));
   MU2IHDX0 g5629__5115 (.IN0(recv_buf_data[0]),
	.IN1(recv_pattern[0]),
	.Q(n_102),
	.S(n_95));
   ON31HDX0 g5630__7482 (.A(recv_divcnt[6]),
	.B(n_1),
	.C(n_80),
	.D(n_10),
	.Q(n_104));
   NO2HDX0 g5631__4733 (.A(n_101),
	.B(n_4),
	.Q(n_103));
   INHDX0 g5640 (.A(n_100),
	.Q(n_99));
   INHDX0 g5641 (.A(n_97),
	.Q(n_98));
   AO211HDX0 g5642__6161 (.A(n_42),
	.B(send_bitcnt[3]),
	.C(n_24),
	.D(n_29),
	.Q(n_96));
   NO3HDX0 g5646__9315 (.A(n_83),
	.B(n_18),
	.C(n_10),
	.Q(n_101));
   NO2HDX0 g5648__9945 (.A(n_95),
	.B(n_4),
	.Q(n_100));
   NA2HDX0 g5649__2883 (.A(n_95),
	.B(resetn),
	.Q(n_97));
   NA2HDX0 g5650__2346 (.A(n_78),
	.B(n_28),
	.Q(n_94));
   NA2HDX0 g5651__1666 (.A(n_79),
	.B(n_28),
	.Q(n_93));
   NA2HDX0 g5652__7410 (.A(n_82),
	.B(n_28),
	.Q(n_92));
   ON211HDX0 g5653__6417 (.A(n_39),
	.B(send_bitcnt[0]),
	.C(n_64),
	.D(n_25),
	.Q(n_91));
   AO221HDX0 g5654__5477 (.A(send_pattern[5]),
	.B(n_40),
	.C(send_pattern[6]),
	.D(n_38),
	.E(n_27),
	.Q(n_90));
   NO2I1HDX0 g5655__2398 (.AN(n_18),
	.B(n_83),
	.Q(n_95));
   AO221HDX0 g5656__5107 (.A(send_pattern[4]),
	.B(n_40),
	.C(send_pattern[5]),
	.D(n_38),
	.E(n_27),
	.Q(n_89));
   AO221HDX0 g5657__6260 (.A(send_pattern[7]),
	.B(n_40),
	.C(send_pattern[8]),
	.D(n_38),
	.E(n_27),
	.Q(n_88));
   AO221HDX0 g5658__4319 (.A(send_pattern[6]),
	.B(n_40),
	.C(send_pattern[7]),
	.D(n_38),
	.E(n_27),
	.Q(n_87));
   AO221HDX0 g5659__8428 (.A(ser_tx),
	.B(n_40),
	.C(send_pattern[1]),
	.D(n_38),
	.E(n_27),
	.Q(n_86));
   AO221HDX0 g5660__5526 (.A(send_bitcnt[2]),
	.B(n_40),
	.C(n_17),
	.D(n_38),
	.E(n_24),
	.Q(n_85));
   AO211HDX0 g5661__6783 (.A(n_40),
	.B(send_pattern[8]),
	.C(n_27),
	.D(n_36),
	.Q(n_84));
   AN222HDX0 g5681__3680 (.A(send_pattern[1]),
	.B(n_40),
	.C(send_pattern[2]),
	.D(n_38),
	.E(n_29),
	.F(reg_dat_di[0]),
	.Q(n_82));
   AN22HDX0 g5682__1617 (.A(n_40),
	.B(send_bitcnt[1]),
	.C(n_38),
	.D(n_7),
	.Q(n_81));
   NA22HDX0 g5683__2802 (.A(recv_divcnt[5]),
	.B(n_12),
	.C(n_59),
	.Q(n_80));
   AN222HDX0 g5684__1705 (.A(send_pattern[2]),
	.B(n_40),
	.C(send_pattern[3]),
	.D(n_38),
	.E(n_29),
	.F(reg_dat_di[1]),
	.Q(n_79));
   AN222HDX0 g5685__5122 (.A(send_pattern[3]),
	.B(n_40),
	.C(send_pattern[4]),
	.D(n_38),
	.E(n_29),
	.F(reg_dat_di[2]),
	.Q(n_78));
   AN211HDX0 g5695__8246 (.A(n_13),
	.B(recv_divcnt[6]),
	.C(recv_divcnt[31]),
	.D(n_60),
	.Q(n_83));
   AND2HDX0 g5700__7098 (.A(n_230),
	.B(n_40),
	.Q(n_77));
   AND2HDX0 g5701__6131 (.A(n_228),
	.B(n_40),
	.Q(n_76));
   AND2HDX0 g5702__1881 (.A(n_226),
	.B(n_40),
	.Q(n_75));
   AND2HDX0 g5703__5115 (.A(n_224),
	.B(n_40),
	.Q(n_74));
   AND2HDX0 g5704__7482 (.A(n_222),
	.B(n_40),
	.Q(n_73));
   AND2HDX0 g5705__4733 (.A(n_40),
	.B(n_208),
	.Q(n_72));
   AND2HDX0 g5706__6161 (.A(n_220),
	.B(n_40),
	.Q(n_71));
   AND2HDX0 g5707__9315 (.A(n_40),
	.B(n_204),
	.Q(n_70));
   AND2HDX0 g5708__9945 (.A(n_40),
	.B(n_211),
	.Q(n_69));
   AND2HDX0 g5709__2883 (.A(n_40),
	.B(n_206),
	.Q(n_68));
   AND2HDX0 g5710__2346 (.A(n_40),
	.B(n_212),
	.Q(n_67));
   AND2HDX0 g5711__1666 (.A(n_218),
	.B(n_40),
	.Q(n_66));
   AND2HDX0 g5712__7410 (.A(n_40),
	.B(n_203),
	.Q(n_65));
   NA2HDX0 g5713__6417 (.A(n_40),
	.B(send_bitcnt[0]),
	.Q(n_64));
   NO2HDX0 g5714__5477 (.A(n_41),
	.B(send_divcnt[0]),
	.Q(n_63));
   AND2HDX0 g5715__2398 (.A(n_40),
	.B(n_205),
	.Q(n_62));
   AND2HDX0 g5716__5107 (.A(n_40),
	.B(n_207),
	.Q(n_61));
   INHDX0 g5717 (.A(n_59),
	.Q(n_60));
   NO2I1HDX0 g5718__6260 (.AN(n_225),
	.B(n_41),
	.Q(n_58));
   NO2I1HDX0 g5719__4319 (.AN(n_210),
	.B(n_41),
	.Q(n_57));
   NO2I1HDX0 g5720__8428 (.AN(n_232),
	.B(n_41),
	.Q(n_56));
   NO2I1HDX0 g5721__5526 (.AN(n_213),
	.B(n_41),
	.Q(n_55));
   NO2I1HDX0 g5722__6783 (.AN(n_214),
	.B(n_41),
	.Q(n_54));
   NO2I1HDX0 g5723__3680 (.AN(n_215),
	.B(n_41),
	.Q(n_53));
   NO2I1HDX0 g5724__1617 (.AN(n_219),
	.B(n_41),
	.Q(n_52));
   NO2I1HDX0 g5725__2802 (.AN(n_221),
	.B(n_41),
	.Q(n_51));
   NO2I1HDX0 g5726__1705 (.AN(n_223),
	.B(n_41),
	.Q(n_50));
   NO2I1HDX0 g5727__5122 (.AN(n_209),
	.B(n_41),
	.Q(n_49));
   NO2I1HDX0 g5728__8246 (.AN(n_227),
	.B(n_41),
	.Q(n_48));
   NO2I1HDX0 g5729__7098 (.AN(n_229),
	.B(n_41),
	.Q(n_47));
   NO2I1HDX0 g5730__6131 (.AN(n_217),
	.B(n_41),
	.Q(n_46));
   NO2I1HDX0 g5731__1881 (.AN(n_231),
	.B(n_41),
	.Q(n_45));
   NO2I1HDX0 g5732__5115 (.AN(n_233),
	.B(n_41),
	.Q(n_44));
   NO2I1HDX0 g5733__7482 (.AN(n_216),
	.B(n_41),
	.Q(n_43));
   ON21HDX0 g5734__4733 (.A(n_39),
	.B(n_14),
	.C(n_41),
	.Q(n_42));
   NO3HDX0 g5735__6161 (.A(n_37),
	.B(recv_divcnt[27]),
	.C(recv_divcnt[26]),
	.Q(n_59));
   INHDX0 g5736 (.A(n_41),
	.Q(n_40));
   NA3I1HDX0 g5737__9315 (.AN(n_36),
	.B(n_22),
	.C(n_28),
	.Q(n_41));
   INHDX0 g5738 (.A(n_39),
	.Q(n_38));
   NA2HDX0 g5739__9945 (.A(n_36),
	.B(resetn),
	.Q(n_39));
   NA6I5HDX0 g5740__2883 (.AN(recv_divcnt[25]),
	.BN(recv_divcnt[24]),
	.CN(recv_divcnt[9]),
	.DN(recv_divcnt[28]),
	.EN(recv_divcnt[29]),
	.F(n_33),
	.Q(n_37));
   NO2HDX0 g5741__2346 (.A(n_35),
	.B(n_21),
	.Q(n_36));
   AN211HDX0 g5742__1666 (.A(n_11),
	.B(send_divcnt[6]),
	.C(send_divcnt[29]),
	.D(n_34),
	.Q(n_35));
   OR6HDX0 g5743__7410 (.A(n_31),
	.B(send_divcnt[28]),
	.C(send_divcnt[10]),
	.D(send_divcnt[27]),
	.E(send_divcnt[30]),
	.F(send_divcnt[17]),
	.Q(n_34));
   NO3HDX0 g5744__6417 (.A(n_32),
	.B(recv_divcnt[11]),
	.C(recv_divcnt[10]),
	.Q(n_33));
   NA6I5HDX0 g5745__5477 (.AN(recv_divcnt[30]),
	.BN(recv_divcnt[8]),
	.CN(recv_divcnt[23]),
	.DN(recv_divcnt[12]),
	.EN(recv_divcnt[7]),
	.F(n_26),
	.Q(n_32));
   NA5I3HDX0 g5747__2398 (.AN(send_divcnt[15]),
	.BN(send_divcnt[16]),
	.CN(send_divcnt[13]),
	.D(n_16),
	.E(n_23),
	.Q(n_31));
   MU2HDX0 g5748__5107 (.IN0(n_4),
	.IN1(send_dummy),
	.Q(n_30),
	.S(n_28));
   NO2HDX0 g5750__6260 (.A(n_27),
	.B(n_22),
	.Q(n_29));
   INHDX0 g5751 (.A(n_28),
	.Q(n_27));
   NO2HDX0 g5752__4319 (.A(n_24),
	.B(n_4),
	.Q(n_28));
   NO3HDX0 g5753__8428 (.A(n_20),
	.B(recv_divcnt[18]),
	.C(recv_divcnt[17]),
	.Q(n_26));
   INHDX0 g5754 (.A(n_25),
	.Q(n_24));
   NO3HDX0 g5755__5526 (.A(n_19),
	.B(send_divcnt[21]),
	.C(send_divcnt[20]),
	.Q(n_23));
   NA3HDX0 g5756__6783 (.A(n_21),
	.B(send_dummy),
	.C(resetn),
	.Q(n_25));
   NA2HDX0 g5757__3680 (.A(n_21),
	.B(reg_dat_we),
	.Q(n_22));
   NO2I1HDX0 g5758__1617 (.AN(n_14),
	.B(send_bitcnt[3]),
	.Q(n_21));
   NA6I5HDX0 g5759__2802 (.AN(recv_divcnt[22]),
	.BN(recv_divcnt[21]),
	.CN(recv_divcnt[19]),
	.DN(recv_divcnt[15]),
	.EN(recv_divcnt[16]),
	.F(n_8),
	.Q(n_20));
   NA6I5HDX0 g5760__1705 (.AN(send_divcnt[25]),
	.BN(send_divcnt[24]),
	.CN(send_divcnt[22]),
	.DN(send_divcnt[18]),
	.EN(send_divcnt[19]),
	.F(n_9),
	.Q(n_19));
   NO4I2HDX0 g5761__5122 (.AN(recv_state[1]),
	.BN(recv_state[3]),
	.C(n_5),
	.D(recv_state[2]),
	.Q(n_18));
   AO21HDX0 g5762__8246 (.A(send_bitcnt[2]),
	.B(n_6),
	.C(n_14),
	.Q(n_17));
   NO6HDX0 g5763__7098 (.A(send_divcnt[8]),
	.B(send_divcnt[9]),
	.C(send_divcnt[14]),
	.D(send_divcnt[7]),
	.E(send_divcnt[11]),
	.F(send_divcnt[12]),
	.Q(n_16));
   NA2HDX0 g5764__6131 (.A(n_5),
	.B(recv_state[2]),
	.Q(n_15));
   NO2HDX0 g5765__1881 (.A(n_6),
	.B(send_bitcnt[2]),
	.Q(n_14));
   AO21HDX0 g5766__5115 (.A(recv_divcnt[4]),
	.B(recv_divcnt[3]),
	.C(recv_divcnt[5]),
	.Q(n_13));
   AO21HDX0 g5767__7482 (.A(recv_divcnt[2]),
	.B(recv_divcnt[3]),
	.C(recv_divcnt[4]),
	.Q(n_12));
   AO21HDX0 g5768__4733 (.A(send_divcnt[4]),
	.B(send_divcnt[3]),
	.C(send_divcnt[5]),
	.Q(n_11));
   NO3HDX0 g5769__6161 (.A(send_divcnt[26]),
	.B(send_divcnt[23]),
	.C(send_divcnt[31]),
	.Q(n_9));
   NO3HDX0 g5770__9315 (.A(recv_divcnt[13]),
	.B(recv_divcnt[20]),
	.C(recv_divcnt[14]),
	.Q(n_8));
   NA22HDX0 g5771__9945 (.A(send_bitcnt[1]),
	.B(send_bitcnt[0]),
	.C(n_6),
	.Q(n_7));
   NO3HDX0 g5772__2883 (.A(recv_state[1]),
	.B(recv_state[2]),
	.C(recv_state[3]),
	.Q(n_10));
   OR2HDX0 g5773__2346 (.A(send_bitcnt[1]),
	.B(send_bitcnt[0]),
	.Q(n_6));
   NO2HDX0 g5774__1666 (.A(n_1),
	.B(n_2),
	.Q(n_5));
   INHDX0 g5778 (.A(resetn),
	.Q(n_4));
   DFRHDX0 recv_buf_valid_reg (.C(clk),
	.D(n_114),
	.Q(buf_valid),
	.QN(n_3));
   DFRHDX0 \recv_state_reg[0]  (.C(clk),
	.D(n_165),
	.Q(recv_state[0]),
	.QN(n_1));
   DFRHDX0 \recv_state_reg[1]  (.C(clk),
	.D(n_168),
	.Q(recv_state[1]),
	.QN(n_2));
   NA3I1HDX0 g2__7410 (.AN(n_29),
	.B(n_81),
	.C(n_25),
	.Q(n_0));
   EO2HDX0 inc_add_80_31_g714__6417 (.A(inc_add_80_31_n_58),
	.B(recv_divcnt[31]),
	.Q(n_195));
   HAHDX0 inc_add_80_31_g715__5477 (.A(inc_add_80_31_n_56),
	.B(recv_divcnt[30]),
	.CO(inc_add_80_31_n_58),
	.S(n_194));
   HAHDX0 inc_add_80_31_g716__2398 (.A(inc_add_80_31_n_54),
	.B(recv_divcnt[29]),
	.CO(inc_add_80_31_n_56),
	.S(n_193));
   HAHDX0 inc_add_80_31_g717__5107 (.A(inc_add_80_31_n_52),
	.B(recv_divcnt[28]),
	.CO(inc_add_80_31_n_54),
	.S(n_192));
   HAHDX0 inc_add_80_31_g718__6260 (.A(inc_add_80_31_n_50),
	.B(recv_divcnt[27]),
	.CO(inc_add_80_31_n_52),
	.S(n_191));
   HAHDX0 inc_add_80_31_g719__4319 (.A(inc_add_80_31_n_48),
	.B(recv_divcnt[26]),
	.CO(inc_add_80_31_n_50),
	.S(n_190));
   HAHDX0 inc_add_80_31_g720__8428 (.A(inc_add_80_31_n_46),
	.B(recv_divcnt[25]),
	.CO(inc_add_80_31_n_48),
	.S(n_189));
   HAHDX0 inc_add_80_31_g721__5526 (.A(inc_add_80_31_n_44),
	.B(recv_divcnt[24]),
	.CO(inc_add_80_31_n_46),
	.S(n_188));
   HAHDX0 inc_add_80_31_g722__6783 (.A(inc_add_80_31_n_42),
	.B(recv_divcnt[23]),
	.CO(inc_add_80_31_n_44),
	.S(n_187));
   HAHDX0 inc_add_80_31_g723__3680 (.A(inc_add_80_31_n_40),
	.B(recv_divcnt[22]),
	.CO(inc_add_80_31_n_42),
	.S(n_186));
   HAHDX0 inc_add_80_31_g724__1617 (.A(inc_add_80_31_n_38),
	.B(recv_divcnt[21]),
	.CO(inc_add_80_31_n_40),
	.S(n_185));
   HAHDX0 inc_add_80_31_g725__2802 (.A(inc_add_80_31_n_36),
	.B(recv_divcnt[20]),
	.CO(inc_add_80_31_n_38),
	.S(n_184));
   HAHDX0 inc_add_80_31_g726__1705 (.A(inc_add_80_31_n_34),
	.B(recv_divcnt[19]),
	.CO(inc_add_80_31_n_36),
	.S(n_183));
   HAHDX0 inc_add_80_31_g727__5122 (.A(inc_add_80_31_n_32),
	.B(recv_divcnt[18]),
	.CO(inc_add_80_31_n_34),
	.S(n_182));
   HAHDX0 inc_add_80_31_g728__8246 (.A(inc_add_80_31_n_30),
	.B(recv_divcnt[17]),
	.CO(inc_add_80_31_n_32),
	.S(n_181));
   HAHDX0 inc_add_80_31_g729__7098 (.A(inc_add_80_31_n_28),
	.B(recv_divcnt[16]),
	.CO(inc_add_80_31_n_30),
	.S(n_180));
   HAHDX0 inc_add_80_31_g730__6131 (.A(inc_add_80_31_n_26),
	.B(recv_divcnt[15]),
	.CO(inc_add_80_31_n_28),
	.S(n_179));
   HAHDX0 inc_add_80_31_g731__1881 (.A(inc_add_80_31_n_24),
	.B(recv_divcnt[14]),
	.CO(inc_add_80_31_n_26),
	.S(n_178));
   HAHDX0 inc_add_80_31_g732__5115 (.A(inc_add_80_31_n_22),
	.B(recv_divcnt[13]),
	.CO(inc_add_80_31_n_24),
	.S(n_177));
   HAHDX0 inc_add_80_31_g733__7482 (.A(inc_add_80_31_n_20),
	.B(recv_divcnt[12]),
	.CO(inc_add_80_31_n_22),
	.S(n_176));
   HAHDX0 inc_add_80_31_g734__4733 (.A(inc_add_80_31_n_18),
	.B(recv_divcnt[11]),
	.CO(inc_add_80_31_n_20),
	.S(n_175));
   HAHDX0 inc_add_80_31_g735__6161 (.A(inc_add_80_31_n_16),
	.B(recv_divcnt[10]),
	.CO(inc_add_80_31_n_18),
	.S(n_174));
   HAHDX0 inc_add_80_31_g736__9315 (.A(inc_add_80_31_n_14),
	.B(recv_divcnt[9]),
	.CO(inc_add_80_31_n_16),
	.S(n_173));
   HAHDX0 inc_add_80_31_g737__9945 (.A(inc_add_80_31_n_12),
	.B(recv_divcnt[8]),
	.CO(inc_add_80_31_n_14),
	.S(n_172));
   HAHDX0 inc_add_80_31_g738__2883 (.A(inc_add_80_31_n_10),
	.B(recv_divcnt[7]),
	.CO(inc_add_80_31_n_12),
	.S(n_202));
   HAHDX0 inc_add_80_31_g739__2346 (.A(inc_add_80_31_n_8),
	.B(recv_divcnt[6]),
	.CO(inc_add_80_31_n_10),
	.S(n_201));
   HAHDX0 inc_add_80_31_g740__1666 (.A(inc_add_80_31_n_6),
	.B(recv_divcnt[5]),
	.CO(inc_add_80_31_n_8),
	.S(n_200));
   HAHDX0 inc_add_80_31_g741__7410 (.A(inc_add_80_31_n_4),
	.B(recv_divcnt[4]),
	.CO(inc_add_80_31_n_6),
	.S(n_199));
   HAHDX0 inc_add_80_31_g742__6417 (.A(inc_add_80_31_n_2),
	.B(recv_divcnt[3]),
	.CO(inc_add_80_31_n_4),
	.S(n_198));
   HAHDX0 inc_add_80_31_g743__5477 (.A(inc_add_80_31_n_0),
	.B(recv_divcnt[2]),
	.CO(inc_add_80_31_n_2),
	.S(n_197));
   HAHDX0 inc_add_80_31_g744__2398 (.A(recv_divcnt[0]),
	.B(recv_divcnt[1]),
	.CO(inc_add_80_31_n_0),
	.S(n_196));
   EO2HDX0 inc_add_118_30_g714__5107 (.A(inc_add_118_30_n_58),
	.B(send_divcnt[31]),
	.Q(n_233));
   HAHDX0 inc_add_118_30_g715__6260 (.A(inc_add_118_30_n_56),
	.B(send_divcnt[30]),
	.CO(inc_add_118_30_n_58),
	.S(n_232));
   HAHDX0 inc_add_118_30_g716__4319 (.A(inc_add_118_30_n_54),
	.B(send_divcnt[29]),
	.CO(inc_add_118_30_n_56),
	.S(n_231));
   HAHDX0 inc_add_118_30_g717__8428 (.A(inc_add_118_30_n_52),
	.B(send_divcnt[28]),
	.CO(inc_add_118_30_n_54),
	.S(n_230));
   HAHDX0 inc_add_118_30_g718__5526 (.A(inc_add_118_30_n_50),
	.B(send_divcnt[27]),
	.CO(inc_add_118_30_n_52),
	.S(n_229));
   HAHDX0 inc_add_118_30_g719__6783 (.A(inc_add_118_30_n_48),
	.B(send_divcnt[26]),
	.CO(inc_add_118_30_n_50),
	.S(n_228));
   HAHDX0 inc_add_118_30_g720__3680 (.A(inc_add_118_30_n_46),
	.B(send_divcnt[25]),
	.CO(inc_add_118_30_n_48),
	.S(n_227));
   HAHDX0 inc_add_118_30_g721__1617 (.A(inc_add_118_30_n_44),
	.B(send_divcnt[24]),
	.CO(inc_add_118_30_n_46),
	.S(n_226));
   HAHDX0 inc_add_118_30_g722__2802 (.A(inc_add_118_30_n_42),
	.B(send_divcnt[23]),
	.CO(inc_add_118_30_n_44),
	.S(n_225));
   HAHDX0 inc_add_118_30_g723__1705 (.A(inc_add_118_30_n_40),
	.B(send_divcnt[22]),
	.CO(inc_add_118_30_n_42),
	.S(n_224));
   HAHDX0 inc_add_118_30_g724__5122 (.A(inc_add_118_30_n_38),
	.B(send_divcnt[21]),
	.CO(inc_add_118_30_n_40),
	.S(n_223));
   HAHDX0 inc_add_118_30_g725__8246 (.A(inc_add_118_30_n_36),
	.B(send_divcnt[20]),
	.CO(inc_add_118_30_n_38),
	.S(n_222));
   HAHDX0 inc_add_118_30_g726__7098 (.A(inc_add_118_30_n_34),
	.B(send_divcnt[19]),
	.CO(inc_add_118_30_n_36),
	.S(n_221));
   HAHDX0 inc_add_118_30_g727__6131 (.A(inc_add_118_30_n_32),
	.B(send_divcnt[18]),
	.CO(inc_add_118_30_n_34),
	.S(n_220));
   HAHDX0 inc_add_118_30_g728__1881 (.A(inc_add_118_30_n_30),
	.B(send_divcnt[17]),
	.CO(inc_add_118_30_n_32),
	.S(n_219));
   HAHDX0 inc_add_118_30_g729__5115 (.A(inc_add_118_30_n_28),
	.B(send_divcnt[16]),
	.CO(inc_add_118_30_n_30),
	.S(n_218));
   HAHDX0 inc_add_118_30_g730__7482 (.A(inc_add_118_30_n_26),
	.B(send_divcnt[15]),
	.CO(inc_add_118_30_n_28),
	.S(n_217));
   HAHDX0 inc_add_118_30_g731__4733 (.A(inc_add_118_30_n_24),
	.B(send_divcnt[14]),
	.CO(inc_add_118_30_n_26),
	.S(n_216));
   HAHDX0 inc_add_118_30_g732__6161 (.A(inc_add_118_30_n_22),
	.B(send_divcnt[13]),
	.CO(inc_add_118_30_n_24),
	.S(n_215));
   HAHDX0 inc_add_118_30_g733__9315 (.A(inc_add_118_30_n_20),
	.B(send_divcnt[12]),
	.CO(inc_add_118_30_n_22),
	.S(n_214));
   HAHDX0 inc_add_118_30_g734__9945 (.A(inc_add_118_30_n_18),
	.B(send_divcnt[11]),
	.CO(inc_add_118_30_n_20),
	.S(n_213));
   HAHDX0 inc_add_118_30_g735__2883 (.A(inc_add_118_30_n_16),
	.B(send_divcnt[10]),
	.CO(inc_add_118_30_n_18),
	.S(n_212));
   HAHDX0 inc_add_118_30_g736__2346 (.A(inc_add_118_30_n_14),
	.B(send_divcnt[9]),
	.CO(inc_add_118_30_n_16),
	.S(n_211));
   HAHDX0 inc_add_118_30_g737__1666 (.A(inc_add_118_30_n_12),
	.B(send_divcnt[8]),
	.CO(inc_add_118_30_n_14),
	.S(n_210));
   HAHDX0 inc_add_118_30_g738__7410 (.A(inc_add_118_30_n_10),
	.B(send_divcnt[7]),
	.CO(inc_add_118_30_n_12),
	.S(n_209));
   HAHDX0 inc_add_118_30_g739__6417 (.A(inc_add_118_30_n_8),
	.B(send_divcnt[6]),
	.CO(inc_add_118_30_n_10),
	.S(n_208));
   HAHDX0 inc_add_118_30_g740__5477 (.A(inc_add_118_30_n_6),
	.B(send_divcnt[5]),
	.CO(inc_add_118_30_n_8),
	.S(n_207));
   HAHDX0 inc_add_118_30_g741__2398 (.A(inc_add_118_30_n_4),
	.B(send_divcnt[4]),
	.CO(inc_add_118_30_n_6),
	.S(n_206));
   HAHDX0 inc_add_118_30_g742__5107 (.A(inc_add_118_30_n_2),
	.B(send_divcnt[3]),
	.CO(inc_add_118_30_n_4),
	.S(n_205));
   HAHDX0 inc_add_118_30_g743__6260 (.A(inc_add_118_30_n_0),
	.B(send_divcnt[2]),
	.CO(inc_add_118_30_n_2),
	.S(n_204));
   HAHDX0 inc_add_118_30_g744__4319 (.A(send_divcnt[0]),
	.B(send_divcnt[1]),
	.CO(inc_add_118_30_n_0),
	.S(n_203));
endmodule

module top (
	clk, 
	rst_n, 
	rx, 
	tx);
   input clk;
   input rst_n;
   input rx;
   output tx;

   // Internal wires
   wire FE_OFN0_clk;
   wire [31:0] data_to_funky;
   wire [7:0] data_out;
   wire [31:0] dat_do;
   wire UNCONNECTED19;
   wire UNCONNECTED20;
   wire UNCONNECTED21;
   wire UNCONNECTED22;
   wire UNCONNECTED23;
   wire UNCONNECTED24;
   wire UNCONNECTED_HIER_Z17;
   wire UNCONNECTED_HIER_Z18;
   wire UNCONNECTED_HIER_Z19;
   wire UNCONNECTED_HIER_Z20;
   wire UNCONNECTED_HIER_Z21;
   wire UNCONNECTED_HIER_Z22;
   wire UNCONNECTED_HIER_Z23;
   wire UNCONNECTED_HIER_Z24;
   wire UNCONNECTED_HIER_Z25;
   wire UNCONNECTED_HIER_Z26;
   wire UNCONNECTED_HIER_Z27;
   wire UNCONNECTED_HIER_Z28;
   wire UNCONNECTED_HIER_Z29;
   wire UNCONNECTED_HIER_Z30;
   wire UNCONNECTED_HIER_Z31;
   wire UNCONNECTED_HIER_Z32;
   wire UNCONNECTED_HIER_Z33;
   wire UNCONNECTED_HIER_Z34;
   wire UNCONNECTED_HIER_Z35;
   wire UNCONNECTED_HIER_Z36;
   wire UNCONNECTED_HIER_Z37;
   wire UNCONNECTED_HIER_Z38;
   wire UNCONNECTED_HIER_Z39;
   wire UNCONNECTED_HIER_Z40;
   wire UNCONNECTED_HIER_Z41;
   wire UNCONNECTED_HIER_Z42;
   wire UNCONNECTED_HIER_Z43;
   wire UNCONNECTED_HIER_Z44;
   wire UNCONNECTED_HIER_Z45;
   wire UNCONNECTED_HIER_Z46;
   wire UNCONNECTED_HIER_Z47;
   wire UNCONNECTED_HIER_Z48;
   wire UNCONNECTED_HIER_Z49;
   wire UNCONNECTED_HIER_Z50;
   wire UNCONNECTED_HIER_Z51;
   wire UNCONNECTED_HIER_Z52;
   wire UNCONNECTED_HIER_Z53;
   wire UNCONNECTED_HIER_Z54;
   wire UNCONNECTED_HIER_Z55;
   wire data_ready;
   wire read_enable_uart;
   wire read_from_funky;
   wire uart_recv_valid;
   wire wr;

   BUHDX1 FE_OFC0_clk (.A(clk),
	.Q(FE_OFN0_clk));
   funky_cu funky (.clk(clk),
	.rst_n(rst_n),
	.din({ data_to_funky[31],
		data_to_funky[30],
		data_to_funky[29],
		data_to_funky[28],
		data_to_funky[27],
		data_to_funky[26],
		data_to_funky[25],
		data_to_funky[24],
		UNCONNECTED_HIER_Z22,
		UNCONNECTED_HIER_Z21,
		UNCONNECTED_HIER_Z20,
		UNCONNECTED_HIER_Z19,
		UNCONNECTED_HIER_Z18,
		UNCONNECTED_HIER_Z17,
		data_to_funky[17],
		data_to_funky[16],
		data_to_funky[15],
		data_to_funky[14],
		data_to_funky[13],
		data_to_funky[12],
		data_to_funky[11],
		data_to_funky[10],
		data_to_funky[9],
		data_to_funky[8],
		data_to_funky[7],
		data_to_funky[6],
		data_to_funky[5],
		data_to_funky[4],
		data_to_funky[3],
		data_to_funky[2],
		data_to_funky[1],
		data_to_funky[0] }),
	.dout({ UNCONNECTED23,
		UNCONNECTED22,
		UNCONNECTED21,
		UNCONNECTED20,
		UNCONNECTED19,
		data_out[2],
		data_out[1],
		data_out[0] }),
	.done_reading(read_from_funky),
	.juanito_data_available(data_ready),
	.write_result(wr),
	.FE_OFN1_clk(FE_OFN0_clk));
   juanito middleman (.rst_n(rst_n),
	.clk(clk),
	.uart_data_valid(uart_recv_valid),
	.din({ dat_do[7],
		dat_do[6],
		dat_do[5],
		dat_do[4],
		dat_do[3],
		dat_do[2],
		dat_do[1],
		dat_do[0] }),
	.read_enable(read_enable_uart),
	.funky_read(read_from_funky),
	.juanito_data_available(data_ready),
	.data(data_to_funky));
   simpleuart uart (.clk(clk),
	.resetn(rst_n),
	.ser_tx(tx),
	.ser_rx(rx),
	.reg_div_we({ UNCONNECTED_HIER_Z26,
		UNCONNECTED_HIER_Z25,
		UNCONNECTED_HIER_Z24,
		UNCONNECTED_HIER_Z23 }),
	.reg_dat_we(wr),
	.reg_dat_re(read_enable_uart),
	.reg_dat_di({ UNCONNECTED_HIER_Z55,
		UNCONNECTED_HIER_Z54,
		UNCONNECTED_HIER_Z53,
		UNCONNECTED_HIER_Z52,
		UNCONNECTED_HIER_Z51,
		UNCONNECTED_HIER_Z50,
		UNCONNECTED_HIER_Z49,
		UNCONNECTED_HIER_Z48,
		UNCONNECTED_HIER_Z47,
		UNCONNECTED_HIER_Z46,
		UNCONNECTED_HIER_Z45,
		UNCONNECTED_HIER_Z44,
		UNCONNECTED_HIER_Z43,
		UNCONNECTED_HIER_Z42,
		UNCONNECTED_HIER_Z41,
		UNCONNECTED_HIER_Z40,
		UNCONNECTED_HIER_Z39,
		UNCONNECTED_HIER_Z38,
		UNCONNECTED_HIER_Z37,
		UNCONNECTED_HIER_Z36,
		UNCONNECTED_HIER_Z35,
		UNCONNECTED_HIER_Z34,
		UNCONNECTED_HIER_Z33,
		UNCONNECTED_HIER_Z32,
		UNCONNECTED_HIER_Z31,
		UNCONNECTED_HIER_Z30,
		UNCONNECTED_HIER_Z29,
		UNCONNECTED_HIER_Z28,
		UNCONNECTED_HIER_Z27,
		data_out[2],
		data_out[1],
		data_out[0] }),
	.reg_dat_do(dat_do),
	.reg_dat_wait(UNCONNECTED24),
	.buf_valid(uart_recv_valid),
	.FE_OFN0_clk(FE_OFN0_clk));
endmodule

