
// Generated by Cadence Genus(TM) Synthesis Solution 25.10-p002_1
// Generated on: Aug 20 2026 16:20:25 CEST (Aug 20 2026 14:20:25 UTC)

// Verification Directory fv/fca2005 

module chklpyr(year_12, year_34, is_leap_year);
  input [7:0] year_12, year_34;
  output is_leap_year;
  wire [7:0] year_12, year_34;
  wire is_leap_year;
  wire n_0, n_1, n_2, n_3;
  AN311HDX0 g211__2398(.A (n_0), .B (n_2), .C (n_3), .D (year_34[1]),
       .E (year_34[0]), .Q (is_leap_year));
  NO3HDX0 g212__5107(.A (n_1), .B (year_34[7]), .C (year_34[6]), .Q
       (n_3));
  NO2HDX0 g213__6260(.A (year_34[3]), .B (year_34[2]), .Q (n_2));
  NO2HDX0 g214__4319(.A (year_12[1]), .B (year_12[0]), .Q (n_1));
  NO2HDX0 g215__8428(.A (year_34[5]), .B (year_34[4]), .Q (n_0));
endmodule

module lut_month(month, month_lut);
  input [7:0] month;
  output [7:0] month_lut;
  wire [7:0] month;
  wire [7:0] month_lut;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12;
  AN21HDX0 g414__5526(.A (n_10), .B (n_12), .C (n_7), .Q
       (month_lut[2]));
  NO2HDX0 g415__6783(.A (n_9), .B (n_7), .Q (month_lut[1]));
  NO2I1HDX0 g416__3680(.AN (n_11), .B (n_7), .Q (month_lut[0]));
  ON21HDX0 g417__1617(.A (n_8), .B (n_2), .C (month[0]), .Q (n_12));
  ON32HDX0 g418__2802(.A (month[1]), .B (month[0]), .C (n_3), .D (n_5),
       .E (n_4), .Q (n_11));
  AO211HDX0 g419__1705(.A (n_3), .B (month[1]), .C (month[0]), .D
       (n_2), .Q (n_10));
  AN22HDX0 g420__5122(.A (n_6), .B (month[1]), .C (n_1), .D (month[0]),
       .Q (n_9));
  NO2I1HDX0 g421__8246(.AN (month[1]), .B (n_5), .Q (n_8));
  ON21HDX0 g422__7098(.A (month[3]), .B (month[0]), .C (month[2]), .Q
       (n_6));
  OR4HDX0 g423__6131(.A (month[7]), .B (month[5]), .C (month[6]), .D
       (month[4]), .Q (n_7));
  NO2I1HDX0 g424__1881(.AN (month[0]), .B (month[1]), .Q (n_4));
  NA2I1HDX0 g425__5115(.AN (month[3]), .B (month[2]), .Q (n_5));
  NO2HDX0 g426__7482(.A (month[2]), .B (month[3]), .Q (n_1));
  NA2I1HDX0 g427__4733(.AN (month[2]), .B (month[3]), .Q (n_3));
  NO2HDX0 g428__6161(.A (month[2]), .B (month[1]), .Q (n_2));
endmodule

module lut_year(year_12, year_12_lut);
  input [7:0] year_12;
  output [7:0] year_12_lut;
  wire [7:0] year_12;
  wire [7:0] year_12_lut;
  NO2I1HDX0 g31__9315(.AN (year_12[0]), .B (year_12[1]), .Q
       (year_12_lut[2]));
  NO2I1HDX0 g32__9945(.AN (year_12[1]), .B (year_12[0]), .Q
       (year_12_lut[1]));
  OR2HDX0 g33__2883(.A (year_12[1]), .B (year_12[0]), .Q
       (year_12_lut[0]));
endmodule

module mod7(num_in, mod_out);
  input [7:0] num_in;
  output [7:0] mod_out;
  wire [7:0] num_in;
  wire [7:0] mod_out;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20;
  NO2HDX0 g800__2346(.A (n_20), .B (n_17), .Q (mod_out[0]));
  AN311HDX0 g802__1666(.A (n_8), .B (n_14), .C (n_16), .D (n_18), .E
       (n_19), .Q (mod_out[1]));
  EO2HDX0 g803__7410(.A (n_16), .B (n_11), .Q (n_20));
  NO2HDX0 g805__6417(.A (n_16), .B (n_8), .Q (n_19));
  NO2HDX0 g806__5477(.A (n_17), .B (n_11), .Q (n_18));
  NO2HDX0 g807__2398(.A (n_15), .B (n_5), .Q (n_17));
  NA2HDX0 g808__5107(.A (n_15), .B (n_5), .Q (n_16));
  OA21HDX0 g809__6260(.A (n_13), .B (n_9), .C (n_14), .Q (n_15));
  NA2HDX0 g810__4319(.A (n_13), .B (n_9), .Q (n_14));
  HAHDX0 g812__8428(.A (n_10), .B (n_6), .CO (n_13), .S (n_12));
  NA2I1HDX0 g813__5526(.AN (n_8), .B (n_10), .Q (n_11));
  INHDX0 g814(.A (n_7), .Q (n_8));
  FAHDX0 g815__6783(.A (num_in[5]), .B (num_in[2]), .CI (n_2), .CO
       (n_9), .S (n_10));
  HAHDX0 g816__3680(.A (n_3), .B (n_4), .CO (n_6), .S (n_7));
  FAHDX0 g817__1617(.A (num_in[3]), .B (num_in[0]), .CI (num_in[6]),
       .CO (n_4), .S (n_5));
  FAHDX0 g818__2802(.A (num_in[4]), .B (num_in[1]), .CI (num_in[7]),
       .CO (n_2), .S (n_3));
  NO22HDX0 g2__1705(.A (n_19), .B (n_12), .C (n_18), .Q (mod_out[2]));
endmodule

module fca2005(day, month, year_12, year_34, weekday);
  input [7:0] day, month, year_12, year_34;
  output [7:0] weekday;
  wire [7:0] day, month, year_12, year_34;
  wire [7:0] weekday;
  wire [7:0] lut_month_wire;
  wire [7:0] year_12_lut;
  wire [7:0] total_sum;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED_HIER_Z;
  wire UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z2,
       UNCONNECTED_HIER_Z3, UNCONNECTED_HIER_Z4, UNCONNECTED_HIER_Z5,
       UNCONNECTED_HIER_Z6, UNCONNECTED_HIER_Z7;
  wire UNCONNECTED_HIER_Z8, UNCONNECTED_HIER_Z9, UNCONNECTED_HIER_Z10,
       csa_tree_ADD_TC_OP_3_groupi_n_0,
       csa_tree_ADD_TC_OP_3_groupi_n_2,
       csa_tree_ADD_TC_OP_3_groupi_n_3,
       csa_tree_ADD_TC_OP_3_groupi_n_4, csa_tree_ADD_TC_OP_3_groupi_n_5;
  wire csa_tree_ADD_TC_OP_3_groupi_n_6,
       csa_tree_ADD_TC_OP_3_groupi_n_7,
       csa_tree_ADD_TC_OP_3_groupi_n_8,
       csa_tree_ADD_TC_OP_3_groupi_n_9,
       csa_tree_ADD_TC_OP_3_groupi_n_10,
       csa_tree_ADD_TC_OP_3_groupi_n_11,
       csa_tree_ADD_TC_OP_3_groupi_n_12,
       csa_tree_ADD_TC_OP_3_groupi_n_13;
  wire csa_tree_ADD_TC_OP_3_groupi_n_14,
       csa_tree_ADD_TC_OP_3_groupi_n_15,
       csa_tree_ADD_TC_OP_3_groupi_n_16,
       csa_tree_ADD_TC_OP_3_groupi_n_17,
       csa_tree_ADD_TC_OP_3_groupi_n_18,
       csa_tree_ADD_TC_OP_3_groupi_n_19,
       csa_tree_ADD_TC_OP_3_groupi_n_20,
       csa_tree_ADD_TC_OP_3_groupi_n_21;
  wire csa_tree_ADD_TC_OP_3_groupi_n_22,
       csa_tree_ADD_TC_OP_3_groupi_n_23,
       csa_tree_ADD_TC_OP_3_groupi_n_24,
       csa_tree_ADD_TC_OP_3_groupi_n_25,
       csa_tree_ADD_TC_OP_3_groupi_n_26,
       csa_tree_ADD_TC_OP_3_groupi_n_27,
       csa_tree_ADD_TC_OP_3_groupi_n_28,
       csa_tree_ADD_TC_OP_3_groupi_n_29;
  wire csa_tree_ADD_TC_OP_3_groupi_n_30,
       csa_tree_ADD_TC_OP_3_groupi_n_31,
       csa_tree_ADD_TC_OP_3_groupi_n_32,
       csa_tree_ADD_TC_OP_3_groupi_n_33,
       csa_tree_ADD_TC_OP_3_groupi_n_34,
       csa_tree_ADD_TC_OP_3_groupi_n_36,
       csa_tree_ADD_TC_OP_3_groupi_n_37,
       csa_tree_ADD_TC_OP_3_groupi_n_38;
  wire csa_tree_ADD_TC_OP_3_groupi_n_39,
       csa_tree_ADD_TC_OP_3_groupi_n_40,
       csa_tree_ADD_TC_OP_3_groupi_n_42,
       csa_tree_ADD_TC_OP_3_groupi_n_43,
       csa_tree_ADD_TC_OP_3_groupi_n_44,
       csa_tree_ADD_TC_OP_3_groupi_n_46,
       csa_tree_ADD_TC_OP_3_groupi_n_48,
       csa_tree_ADD_TC_OP_3_groupi_n_50;
  wire csa_tree_ADD_TC_OP_3_groupi_n_52, is_leap_year_wire, n_0, n_1,
       n_84;
  assign weekday[3] = 1'b0;
  assign weekday[4] = 1'b0;
  assign weekday[5] = 1'b0;
  assign weekday[6] = 1'b0;
  assign weekday[7] = 1'b0;
  chklpyr chklpyr(.year_12 ({UNCONNECTED_HIER_Z4, UNCONNECTED_HIER_Z3,
       UNCONNECTED_HIER_Z2, UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z0,
       UNCONNECTED_HIER_Z, year_12[1:0]}), .year_34 (year_34),
       .is_leap_year (is_leap_year_wire));
  lut_month lut_month(.month (month), .month_lut ({UNCONNECTED3,
       UNCONNECTED2, UNCONNECTED1, UNCONNECTED0, UNCONNECTED,
       lut_month_wire[2:0]}));
  lut_year lut_yearr(.year_12 ({UNCONNECTED_HIER_Z10,
       UNCONNECTED_HIER_Z9, UNCONNECTED_HIER_Z8, UNCONNECTED_HIER_Z7,
       UNCONNECTED_HIER_Z6, UNCONNECTED_HIER_Z5, year_12[1:0]}),
       .year_12_lut ({UNCONNECTED8, UNCONNECTED7, UNCONNECTED6,
       UNCONNECTED5, UNCONNECTED4, year_12_lut[2:0]}));
  mod7 mod7_total(.num_in (total_sum), .mod_out ({UNCONNECTED13,
       UNCONNECTED12, UNCONNECTED11, UNCONNECTED10, UNCONNECTED9,
       weekday[2:0]}));
  NA4I3HDX0 g177__8246(.AN (month[4]), .BN (month[3]), .CN (month[2]),
       .D (is_leap_year_wire), .Q (n_1));
  EO2HDX0 g178__7098(.A (month[1]), .B (month[0]), .Q (n_0));
  EN3HDX0 csa_tree_ADD_TC_OP_3_groupi_g1194__6131(.A
       (csa_tree_ADD_TC_OP_3_groupi_n_52), .B
       (csa_tree_ADD_TC_OP_3_groupi_n_30), .C
       (csa_tree_ADD_TC_OP_3_groupi_n_15), .Q (total_sum[7]));
  FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1195__1881(.A
       (csa_tree_ADD_TC_OP_3_groupi_n_36), .B
       (csa_tree_ADD_TC_OP_3_groupi_n_31), .CI
       (csa_tree_ADD_TC_OP_3_groupi_n_50), .CO
       (csa_tree_ADD_TC_OP_3_groupi_n_52), .S (total_sum[6]));
  FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1196__5115(.A
       (csa_tree_ADD_TC_OP_3_groupi_n_37), .B
       (csa_tree_ADD_TC_OP_3_groupi_n_32), .CI
       (csa_tree_ADD_TC_OP_3_groupi_n_48), .CO
       (csa_tree_ADD_TC_OP_3_groupi_n_50), .S (total_sum[5]));
  FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1197__7482(.A
       (csa_tree_ADD_TC_OP_3_groupi_n_42), .B
       (csa_tree_ADD_TC_OP_3_groupi_n_33), .CI
       (csa_tree_ADD_TC_OP_3_groupi_n_46), .CO
       (csa_tree_ADD_TC_OP_3_groupi_n_48), .S (total_sum[4]));
  FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1198__4733(.A
       (csa_tree_ADD_TC_OP_3_groupi_n_43), .B
       (csa_tree_ADD_TC_OP_3_groupi_n_38), .CI
       (csa_tree_ADD_TC_OP_3_groupi_n_44), .CO
       (csa_tree_ADD_TC_OP_3_groupi_n_46), .S (total_sum[3]));
  FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1199__6161(.A
       (csa_tree_ADD_TC_OP_3_groupi_n_39), .B
       (csa_tree_ADD_TC_OP_3_groupi_n_28), .CI
       (csa_tree_ADD_TC_OP_3_groupi_n_40), .CO
       (csa_tree_ADD_TC_OP_3_groupi_n_44), .S (total_sum[2]));
  FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1200__9315(.A
       (csa_tree_ADD_TC_OP_3_groupi_n_25), .B
       (csa_tree_ADD_TC_OP_3_groupi_n_8), .CI
       (csa_tree_ADD_TC_OP_3_groupi_n_26), .CO
       (csa_tree_ADD_TC_OP_3_groupi_n_42), .S
       (csa_tree_ADD_TC_OP_3_groupi_n_43));
  FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1201__9945(.A
       (csa_tree_ADD_TC_OP_3_groupi_n_34), .B
       (csa_tree_ADD_TC_OP_3_groupi_n_20), .CI
       (csa_tree_ADD_TC_OP_3_groupi_n_29), .CO
       (csa_tree_ADD_TC_OP_3_groupi_n_40), .S (total_sum[1]));
  FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1202__2883(.A
       (lut_month_wire[2]), .B (csa_tree_ADD_TC_OP_3_groupi_n_22), .CI
       (csa_tree_ADD_TC_OP_3_groupi_n_27), .CO
       (csa_tree_ADD_TC_OP_3_groupi_n_38), .S
       (csa_tree_ADD_TC_OP_3_groupi_n_39));
  FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1203__2346(.A
       (csa_tree_ADD_TC_OP_3_groupi_n_16), .B
       (csa_tree_ADD_TC_OP_3_groupi_n_0), .CI
       (csa_tree_ADD_TC_OP_3_groupi_n_19), .CO
       (csa_tree_ADD_TC_OP_3_groupi_n_36), .S
       (csa_tree_ADD_TC_OP_3_groupi_n_37));
  FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1204__1666(.A (n_84), .B
       (csa_tree_ADD_TC_OP_3_groupi_n_12), .CI
       (csa_tree_ADD_TC_OP_3_groupi_n_21), .CO
       (csa_tree_ADD_TC_OP_3_groupi_n_34), .S (total_sum[0]));
  FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1205__7410(.A
       (csa_tree_ADD_TC_OP_3_groupi_n_17), .B
       (csa_tree_ADD_TC_OP_3_groupi_n_3), .CI
       (csa_tree_ADD_TC_OP_3_groupi_n_24), .CO
       (csa_tree_ADD_TC_OP_3_groupi_n_32), .S
       (csa_tree_ADD_TC_OP_3_groupi_n_33));
  FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1206__6417(.A
       (csa_tree_ADD_TC_OP_3_groupi_n_10), .B (year_34[7]), .CI
       (csa_tree_ADD_TC_OP_3_groupi_n_18), .CO
       (csa_tree_ADD_TC_OP_3_groupi_n_30), .S
       (csa_tree_ADD_TC_OP_3_groupi_n_31));
  FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1207__5477(.A
       (csa_tree_ADD_TC_OP_3_groupi_n_23), .B
       (csa_tree_ADD_TC_OP_3_groupi_n_9), .CI (lut_month_wire[1]), .CO
       (csa_tree_ADD_TC_OP_3_groupi_n_28), .S
       (csa_tree_ADD_TC_OP_3_groupi_n_29));
  FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1208__2398(.A
       (csa_tree_ADD_TC_OP_3_groupi_n_14), .B
       (csa_tree_ADD_TC_OP_3_groupi_n_4), .CI
       (csa_tree_ADD_TC_OP_3_groupi_n_11), .CO
       (csa_tree_ADD_TC_OP_3_groupi_n_26), .S
       (csa_tree_ADD_TC_OP_3_groupi_n_27));
  FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1209__5107(.A
       (csa_tree_ADD_TC_OP_3_groupi_n_13), .B (day[3]), .CI
       (csa_tree_ADD_TC_OP_3_groupi_n_7), .CO
       (csa_tree_ADD_TC_OP_3_groupi_n_24), .S
       (csa_tree_ADD_TC_OP_3_groupi_n_25));
  FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1210__6260(.A
       (csa_tree_ADD_TC_OP_3_groupi_n_6), .B (day[1]), .CI
       (year_12_lut[1]), .CO (csa_tree_ADD_TC_OP_3_groupi_n_22), .S
       (csa_tree_ADD_TC_OP_3_groupi_n_23));
  FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1211__4319(.A (year_12_lut[0]),
       .B (day[0]), .CI (lut_month_wire[0]), .CO
       (csa_tree_ADD_TC_OP_3_groupi_n_20), .S
       (csa_tree_ADD_TC_OP_3_groupi_n_21));
  FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1212__8428(.A (year_34[5]), .B
       (day[5]), .CI (year_34[6]), .CO
       (csa_tree_ADD_TC_OP_3_groupi_n_18), .S
       (csa_tree_ADD_TC_OP_3_groupi_n_19));
  FAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1213__5526(.A (year_34[4]), .B
       (day[4]), .CI (csa_tree_ADD_TC_OP_3_groupi_n_2), .CO
       (csa_tree_ADD_TC_OP_3_groupi_n_16), .S
       (csa_tree_ADD_TC_OP_3_groupi_n_17));
  EN3HDX0 csa_tree_ADD_TC_OP_3_groupi_g1214__6783(.A
       (csa_tree_ADD_TC_OP_3_groupi_n_5), .B (year_34[7]), .C (day[7]),
       .Q (csa_tree_ADD_TC_OP_3_groupi_n_15));
  HAHDX0 csa_tree_ADD_TC_OP_3_groupi_g1215__3680(.A (year_34[4]), .B
       (year_34[2]), .CO (csa_tree_ADD_TC_OP_3_groupi_n_13), .S
       (csa_tree_ADD_TC_OP_3_groupi_n_14));
  NA22HDX0 csa_tree_ADD_TC_OP_3_groupi_g1216__1617(.A (year_34[0]), .B
       (year_34[2]), .C (csa_tree_ADD_TC_OP_3_groupi_n_6), .Q
       (csa_tree_ADD_TC_OP_3_groupi_n_12));
  NA22HDX0 csa_tree_ADD_TC_OP_3_groupi_g1217__2802(.A (day[2]), .B
       (year_12_lut[2]), .C (csa_tree_ADD_TC_OP_3_groupi_n_7), .Q
       (csa_tree_ADD_TC_OP_3_groupi_n_11));
  MU2IHDX0 csa_tree_ADD_TC_OP_3_groupi_g1218__1705(.IN0 (year_34[6]),
       .IN1 (csa_tree_ADD_TC_OP_3_groupi_n_2), .S (day[6]), .Q
       (csa_tree_ADD_TC_OP_3_groupi_n_10));
  EN2HDX0 csa_tree_ADD_TC_OP_3_groupi_g1219__5122(.A (year_34[1]), .B
       (year_34[3]), .Q (csa_tree_ADD_TC_OP_3_groupi_n_9));
  EN2HDX0 csa_tree_ADD_TC_OP_3_groupi_g1220__8246(.A (year_34[3]), .B
       (year_34[5]), .Q (csa_tree_ADD_TC_OP_3_groupi_n_8));
  OR2HDX0 csa_tree_ADD_TC_OP_3_groupi_g1221__7098(.A (year_12_lut[2]),
       .B (day[2]), .Q (csa_tree_ADD_TC_OP_3_groupi_n_7));
  OR2HDX0 csa_tree_ADD_TC_OP_3_groupi_g1222__6131(.A (year_34[2]), .B
       (year_34[0]), .Q (csa_tree_ADD_TC_OP_3_groupi_n_6));
  NO2HDX0 csa_tree_ADD_TC_OP_3_groupi_g1223__1881(.A (year_34[6]), .B
       (day[6]), .Q (csa_tree_ADD_TC_OP_3_groupi_n_5));
  OR2HDX0 csa_tree_ADD_TC_OP_3_groupi_g1224__5115(.A (year_34[3]), .B
       (year_34[1]), .Q (csa_tree_ADD_TC_OP_3_groupi_n_4));
  OR2HDX0 csa_tree_ADD_TC_OP_3_groupi_g1225__7482(.A (year_34[5]), .B
       (year_34[3]), .Q (csa_tree_ADD_TC_OP_3_groupi_n_3));
  INHDX0 csa_tree_ADD_TC_OP_3_groupi_g1226(.A (year_34[6]), .Q
       (csa_tree_ADD_TC_OP_3_groupi_n_2));
  INHDX0 csa_tree_ADD_TC_OP_3_groupi_g1228(.A (year_34[7]), .Q
       (csa_tree_ADD_TC_OP_3_groupi_n_0));
  NA5I4HDX0 g2(.AN (month[6]), .BN (month[7]), .CN (n_1), .DN
       (month[5]), .E (n_0), .Q (n_84));
endmodule

