
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point rx rx -type PI PI

//output ports
add mapped point tx tx -type PO PO

//inout ports




//Sequential Pins
add mapped point funky/done_reading/q funky/done_reading_reg/Q -type DLAT DLAT
add mapped point funky/data_buf[6]/q funky/data_buf_reg[6]/Q -type DLAT DLAT
add mapped point funky/data_buf[2]/q funky/data_buf_reg[2]/Q -type DLAT DLAT
add mapped point funky/data_buf[10]/q funky/data_buf_reg[10]/Q -type DLAT DLAT
add mapped point funky/data_buf[9]/q funky/data_buf_reg[9]/Q -type DLAT DLAT
add mapped point funky/data_buf[1]/q funky/data_buf_reg[1]/Q -type DLAT DLAT
add mapped point funky/data_buf[8]/q funky/data_buf_reg[8]/Q -type DLAT DLAT
add mapped point funky/data_buf[17]/q funky/data_buf_reg[17]/Q -type DLAT DLAT
add mapped point funky/data_buf[5]/q funky/data_buf_reg[5]/Q -type DLAT DLAT
add mapped point funky/data_buf[0]/q funky/data_buf_reg[0]/Q -type DLAT DLAT
add mapped point funky/data_buf[16]/q funky/data_buf_reg[16]/Q -type DLAT DLAT
add mapped point funky/data_buf[31]/q funky/data_buf_reg[31]/Q -type DLAT DLAT
add mapped point funky/data_buf[15]/q funky/data_buf_reg[15]/Q -type DLAT DLAT
add mapped point funky/data_buf[30]/q funky/data_buf_reg[30]/Q -type DLAT DLAT
add mapped point funky/data_buf[7]/q funky/data_buf_reg[7]/Q -type DLAT DLAT
add mapped point funky/data_buf[4]/q funky/data_buf_reg[4]/Q -type DLAT DLAT
add mapped point funky/data_buf[14]/q funky/data_buf_reg[14]/Q -type DLAT DLAT
add mapped point funky/data_buf[28]/q funky/data_buf_reg[28]/Q -type DLAT DLAT
add mapped point funky/data_buf[27]/q funky/data_buf_reg[27]/Q -type DLAT DLAT
add mapped point funky/data_buf[13]/q funky/data_buf_reg[13]/Q -type DLAT DLAT
add mapped point funky/data_buf[26]/q funky/data_buf_reg[26]/Q -type DLAT DLAT
add mapped point funky/data_buf[25]/q funky/data_buf_reg[25]/Q -type DLAT DLAT
add mapped point funky/data_buf[3]/q funky/data_buf_reg[3]/Q -type DLAT DLAT
add mapped point funky/data_buf[12]/q funky/data_buf_reg[12]/Q -type DLAT DLAT
add mapped point funky/data_buf[24]/q funky/data_buf_reg[24]/Q -type DLAT DLAT
add mapped point funky/data_buf[11]/q funky/data_buf_reg[11]/Q -type DLAT DLAT
add mapped point funky/data_buf[29]/q funky/data_buf_reg[29]/Q -type DLAT DLAT
add mapped point funky/write_result/q funky/write_result_reg/Q -type DLAT DLAT
add mapped point funky/p_state[0]/q funky/p_state_reg[0]/Q -type DFF DFF
add mapped point funky/p_state[1]/q funky/p_state_reg[1]/Q -type DFF DFF
add mapped point funky/p_state[2]/q funky/p_state_reg[2]/Q -type DFF DFF
add mapped point middleman/data[31]/q middleman/data_reg[31]/Q -type DLAT DLAT
add mapped point middleman/data[30]/q middleman/data_reg[30]/Q -type DLAT DLAT
add mapped point middleman/data[26]/q middleman/data_reg[26]/Q -type DLAT DLAT
add mapped point middleman/data[12]/q middleman/data_reg[12]/Q -type DLAT DLAT
add mapped point middleman/data[11]/q middleman/data_reg[11]/Q -type DLAT DLAT
add mapped point middleman/data[25]/q middleman/data_reg[25]/Q -type DLAT DLAT
add mapped point middleman/data[10]/q middleman/data_reg[10]/Q -type DLAT DLAT
add mapped point middleman/data[9]/q middleman/data_reg[9]/Q -type DLAT DLAT
add mapped point middleman/data[29]/q middleman/data_reg[29]/Q -type DLAT DLAT
add mapped point middleman/data[24]/q middleman/data_reg[24]/Q -type DLAT DLAT
add mapped point middleman/data[8]/q middleman/data_reg[8]/Q -type DLAT DLAT
add mapped point middleman/data[7]/q middleman/data_reg[7]/Q -type DLAT DLAT
add mapped point middleman/data[17]/q middleman/data_reg[17]/Q -type DLAT DLAT
add mapped point middleman/data[6]/q middleman/data_reg[6]/Q -type DLAT DLAT
add mapped point middleman/data[5]/q middleman/data_reg[5]/Q -type DLAT DLAT
add mapped point middleman/data[28]/q middleman/data_reg[28]/Q -type DLAT DLAT
add mapped point middleman/data[16]/q middleman/data_reg[16]/Q -type DLAT DLAT
add mapped point middleman/data[4]/q middleman/data_reg[4]/Q -type DLAT DLAT
add mapped point middleman/data[3]/q middleman/data_reg[3]/Q -type DLAT DLAT
add mapped point middleman/data[15]/q middleman/data_reg[15]/Q -type DLAT DLAT
add mapped point middleman/data[2]/q middleman/data_reg[2]/Q -type DLAT DLAT
add mapped point middleman/data[1]/q middleman/data_reg[1]/Q -type DLAT DLAT
add mapped point middleman/data[27]/q middleman/data_reg[27]/Q -type DLAT DLAT
add mapped point middleman/data[14]/q middleman/data_reg[14]/Q -type DLAT DLAT
add mapped point middleman/data[0]/q middleman/data_reg[0]/Q -type DLAT DLAT
add mapped point middleman/data[13]/q middleman/data_reg[13]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[7]/q middleman/juanito_buffer_reg[7]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[0]/q middleman/juanito_buffer_reg[0]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[1]/q middleman/juanito_buffer_reg[1]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[2]/q middleman/juanito_buffer_reg[2]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[3]/q middleman/juanito_buffer_reg[3]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[4]/q middleman/juanito_buffer_reg[4]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[5]/q middleman/juanito_buffer_reg[5]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[6]/q middleman/juanito_buffer_reg[6]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[28]/q middleman/juanito_buffer_reg[28]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[24]/q middleman/juanito_buffer_reg[24]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[25]/q middleman/juanito_buffer_reg[25]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[26]/q middleman/juanito_buffer_reg[26]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[27]/q middleman/juanito_buffer_reg[27]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[29]/q middleman/juanito_buffer_reg[29]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[30]/q middleman/juanito_buffer_reg[30]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[31]/q middleman/juanito_buffer_reg[31]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[8]/q middleman/juanito_buffer_reg[8]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[9]/q middleman/juanito_buffer_reg[9]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[10]/q middleman/juanito_buffer_reg[10]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[11]/q middleman/juanito_buffer_reg[11]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[12]/q middleman/juanito_buffer_reg[12]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[13]/q middleman/juanito_buffer_reg[13]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[14]/q middleman/juanito_buffer_reg[14]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[15]/q middleman/juanito_buffer_reg[15]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[16]/q middleman/juanito_buffer_reg[16]/Q -type DLAT DLAT
add mapped point middleman/juanito_buffer[17]/q middleman/juanito_buffer_reg[17]/Q -type DLAT DLAT
add mapped point middleman/juanito_data_available/q middleman/juanito_data_available_reg/Q -type DLAT DLAT
add mapped point middleman/read_enable/q middleman/read_enable_reg/Q -type DLAT DLAT
add mapped point middleman/p_state[1]/q middleman/p_state_reg[1]/Q -type DFF DFF
add mapped point middleman/p_state[2]/q middleman/p_state_reg[2]/Q -type DFF DFF
add mapped point middleman/p_state[0]/q middleman/p_state_reg[0]/Q -type DFF DFF
add mapped point middleman/cnt[1]/q middleman/cnt_reg[1]/Q -type DLAT DLAT
add mapped point middleman/cnt[0]/q middleman/cnt_reg[0]/Q -type DLAT DLAT
add mapped point uart/recv_buf_data[0]/q uart/recv_buf_data_reg[0]/Q -type DFF DFF
add mapped point uart/recv_buf_data[1]/q uart/recv_buf_data_reg[1]/Q -type DFF DFF
add mapped point uart/recv_buf_data[2]/q uart/recv_buf_data_reg[2]/Q -type DFF DFF
add mapped point uart/recv_buf_data[3]/q uart/recv_buf_data_reg[3]/Q -type DFF DFF
add mapped point uart/recv_buf_data[4]/q uart/recv_buf_data_reg[4]/Q -type DFF DFF
add mapped point uart/recv_buf_data[5]/q uart/recv_buf_data_reg[5]/Q -type DFF DFF
add mapped point uart/recv_buf_data[6]/q uart/recv_buf_data_reg[6]/Q -type DFF DFF
add mapped point uart/recv_buf_data[7]/q uart/recv_buf_data_reg[7]/Q -type DFF DFF
add mapped point uart/recv_divcnt[0]/q uart/recv_divcnt_reg[0]/Q -type DFF DFF
add mapped point uart/recv_divcnt[1]/q uart/recv_divcnt_reg[1]/Q -type DFF DFF
add mapped point uart/recv_divcnt[2]/q uart/recv_divcnt_reg[2]/Q -type DFF DFF
add mapped point uart/recv_divcnt[3]/q uart/recv_divcnt_reg[3]/Q -type DFF DFF
add mapped point uart/recv_divcnt[4]/q uart/recv_divcnt_reg[4]/Q -type DFF DFF
add mapped point uart/recv_divcnt[5]/q uart/recv_divcnt_reg[5]/Q -type DFF DFF
add mapped point uart/recv_divcnt[6]/q uart/recv_divcnt_reg[6]/Q -type DFF DFF
add mapped point uart/recv_divcnt[7]/q uart/recv_divcnt_reg[7]/Q -type DFF DFF
add mapped point uart/recv_divcnt[8]/q uart/recv_divcnt_reg[8]/Q -type DFF DFF
add mapped point uart/recv_divcnt[9]/q uart/recv_divcnt_reg[9]/Q -type DFF DFF
add mapped point uart/recv_divcnt[10]/q uart/recv_divcnt_reg[10]/Q -type DFF DFF
add mapped point uart/recv_divcnt[11]/q uart/recv_divcnt_reg[11]/Q -type DFF DFF
add mapped point uart/recv_divcnt[12]/q uart/recv_divcnt_reg[12]/Q -type DFF DFF
add mapped point uart/recv_divcnt[13]/q uart/recv_divcnt_reg[13]/Q -type DFF DFF
add mapped point uart/recv_divcnt[14]/q uart/recv_divcnt_reg[14]/Q -type DFF DFF
add mapped point uart/recv_divcnt[15]/q uart/recv_divcnt_reg[15]/Q -type DFF DFF
add mapped point uart/recv_divcnt[16]/q uart/recv_divcnt_reg[16]/Q -type DFF DFF
add mapped point uart/recv_divcnt[17]/q uart/recv_divcnt_reg[17]/Q -type DFF DFF
add mapped point uart/recv_divcnt[18]/q uart/recv_divcnt_reg[18]/Q -type DFF DFF
add mapped point uart/recv_divcnt[19]/q uart/recv_divcnt_reg[19]/Q -type DFF DFF
add mapped point uart/recv_divcnt[20]/q uart/recv_divcnt_reg[20]/Q -type DFF DFF
add mapped point uart/recv_divcnt[21]/q uart/recv_divcnt_reg[21]/Q -type DFF DFF
add mapped point uart/recv_divcnt[22]/q uart/recv_divcnt_reg[22]/Q -type DFF DFF
add mapped point uart/recv_divcnt[23]/q uart/recv_divcnt_reg[23]/Q -type DFF DFF
add mapped point uart/recv_divcnt[24]/q uart/recv_divcnt_reg[24]/Q -type DFF DFF
add mapped point uart/recv_divcnt[25]/q uart/recv_divcnt_reg[25]/Q -type DFF DFF
add mapped point uart/recv_divcnt[26]/q uart/recv_divcnt_reg[26]/Q -type DFF DFF
add mapped point uart/recv_divcnt[27]/q uart/recv_divcnt_reg[27]/Q -type DFF DFF
add mapped point uart/recv_divcnt[28]/q uart/recv_divcnt_reg[28]/Q -type DFF DFF
add mapped point uart/recv_divcnt[29]/q uart/recv_divcnt_reg[29]/Q -type DFF DFF
add mapped point uart/recv_divcnt[30]/q uart/recv_divcnt_reg[30]/Q -type DFF DFF
add mapped point uart/recv_divcnt[31]/q uart/recv_divcnt_reg[31]/Q -type DFF DFF
add mapped point uart/recv_pattern[0]/q uart/recv_pattern_reg[0]/Q -type DFF DFF
add mapped point uart/recv_pattern[1]/q uart/recv_pattern_reg[1]/Q -type DFF DFF
add mapped point uart/recv_pattern[2]/q uart/recv_pattern_reg[2]/Q -type DFF DFF
add mapped point uart/recv_pattern[3]/q uart/recv_pattern_reg[3]/Q -type DFF DFF
add mapped point uart/recv_pattern[4]/q uart/recv_pattern_reg[4]/Q -type DFF DFF
add mapped point uart/recv_pattern[5]/q uart/recv_pattern_reg[5]/Q -type DFF DFF
add mapped point uart/recv_pattern[6]/q uart/recv_pattern_reg[6]/Q -type DFF DFF
add mapped point uart/recv_pattern[7]/q uart/recv_pattern_reg[7]/Q -type DFF DFF
add mapped point uart/recv_state[2]/q uart/recv_state_reg[2]/Q -type DFF DFF
add mapped point uart/recv_state[3]/q uart/recv_state_reg[3]/Q -type DFF DFF
add mapped point uart/send_bitcnt[0]/q uart/send_bitcnt_reg[0]/Q -type DFF DFF
add mapped point uart/send_bitcnt[1]/q uart/send_bitcnt_reg[1]/Q -type DFF DFF
add mapped point uart/send_bitcnt[2]/q uart/send_bitcnt_reg[2]/Q -type DFF DFF
add mapped point uart/send_bitcnt[3]/q uart/send_bitcnt_reg[3]/Q -type DFF DFF
add mapped point uart/send_divcnt[0]/q uart/send_divcnt_reg[0]/Q -type DFF DFF
add mapped point uart/send_divcnt[1]/q uart/send_divcnt_reg[1]/Q -type DFF DFF
add mapped point uart/send_divcnt[2]/q uart/send_divcnt_reg[2]/Q -type DFF DFF
add mapped point uart/send_divcnt[3]/q uart/send_divcnt_reg[3]/Q -type DFF DFF
add mapped point uart/send_divcnt[4]/q uart/send_divcnt_reg[4]/Q -type DFF DFF
add mapped point uart/send_divcnt[5]/q uart/send_divcnt_reg[5]/Q -type DFF DFF
add mapped point uart/send_divcnt[6]/q uart/send_divcnt_reg[6]/Q -type DFF DFF
add mapped point uart/send_divcnt[7]/q uart/send_divcnt_reg[7]/Q -type DFF DFF
add mapped point uart/send_divcnt[8]/q uart/send_divcnt_reg[8]/Q -type DFF DFF
add mapped point uart/send_divcnt[9]/q uart/send_divcnt_reg[9]/Q -type DFF DFF
add mapped point uart/send_divcnt[10]/q uart/send_divcnt_reg[10]/Q -type DFF DFF
add mapped point uart/send_divcnt[11]/q uart/send_divcnt_reg[11]/Q -type DFF DFF
add mapped point uart/send_divcnt[12]/q uart/send_divcnt_reg[12]/Q -type DFF DFF
add mapped point uart/send_divcnt[13]/q uart/send_divcnt_reg[13]/Q -type DFF DFF
add mapped point uart/send_divcnt[14]/q uart/send_divcnt_reg[14]/Q -type DFF DFF
add mapped point uart/send_divcnt[15]/q uart/send_divcnt_reg[15]/Q -type DFF DFF
add mapped point uart/send_divcnt[16]/q uart/send_divcnt_reg[16]/Q -type DFF DFF
add mapped point uart/send_divcnt[17]/q uart/send_divcnt_reg[17]/Q -type DFF DFF
add mapped point uart/send_divcnt[18]/q uart/send_divcnt_reg[18]/Q -type DFF DFF
add mapped point uart/send_divcnt[19]/q uart/send_divcnt_reg[19]/Q -type DFF DFF
add mapped point uart/send_divcnt[20]/q uart/send_divcnt_reg[20]/Q -type DFF DFF
add mapped point uart/send_divcnt[21]/q uart/send_divcnt_reg[21]/Q -type DFF DFF
add mapped point uart/send_divcnt[22]/q uart/send_divcnt_reg[22]/Q -type DFF DFF
add mapped point uart/send_divcnt[23]/q uart/send_divcnt_reg[23]/Q -type DFF DFF
add mapped point uart/send_divcnt[24]/q uart/send_divcnt_reg[24]/Q -type DFF DFF
add mapped point uart/send_divcnt[25]/q uart/send_divcnt_reg[25]/Q -type DFF DFF
add mapped point uart/send_divcnt[26]/q uart/send_divcnt_reg[26]/Q -type DFF DFF
add mapped point uart/send_divcnt[27]/q uart/send_divcnt_reg[27]/Q -type DFF DFF
add mapped point uart/send_divcnt[28]/q uart/send_divcnt_reg[28]/Q -type DFF DFF
add mapped point uart/send_divcnt[29]/q uart/send_divcnt_reg[29]/Q -type DFF DFF
add mapped point uart/send_divcnt[30]/q uart/send_divcnt_reg[30]/Q -type DFF DFF
add mapped point uart/send_divcnt[31]/q uart/send_divcnt_reg[31]/Q -type DFF DFF
add mapped point uart/send_dummy/q uart/send_dummy_reg/Q -type DFF DFF
add mapped point uart/send_pattern[0]/q uart/send_pattern_reg[0]/Q -type DFF DFF
add mapped point uart/send_pattern[1]/q uart/send_pattern_reg[1]/Q -type DFF DFF
add mapped point uart/send_pattern[2]/q uart/send_pattern_reg[2]/Q -type DFF DFF
add mapped point uart/send_pattern[3]/q uart/send_pattern_reg[3]/Q -type DFF DFF
add mapped point uart/send_pattern[4]/q uart/send_pattern_reg[4]/Q -type DFF DFF
add mapped point uart/send_pattern[5]/q uart/send_pattern_reg[5]/Q -type DFF DFF
add mapped point uart/send_pattern[6]/q uart/send_pattern_reg[6]/Q -type DFF DFF
add mapped point uart/send_pattern[7]/q uart/send_pattern_reg[7]/Q -type DFF DFF
add mapped point uart/send_pattern[8]/q uart/send_pattern_reg[8]/Q -type DFF DFF
add mapped point uart/recv_buf_valid/q uart/recv_buf_valid_reg/Q -type DFF DFF
add mapped point uart/recv_state[0]/q uart/recv_state_reg[0]/Q -type DFF DFF
add mapped point uart/recv_state[1]/q uart/recv_state_reg[1]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
