
${syn}/${design}_${tech_node_used}/${design}.v
/apps/DESIGN_KITS/XFAB_xh018/XKIT/xh018/diglibs/D_CELLS_HD/v6_0/verilog/v6_0_0/D_CELLS_HD.v
/apps/DESIGN_KITS/XFAB_xh018/XKIT/xh018/diglibs/D_CELLS_HD/v6_0/verilog/v6_0_0/VLG_PRIMITIVES.v

${tests}/${design}_tb.sv

-sv
-gui
-64bit
-v200x -v93
-access +rwc
-log ${logs}/xrun.log
# -nohistory
# -quiet
-top ${design}_tb
-timescale 1ns/1ps

-sdf_cmd_file ${scr}/cmd/sdf_syn.cmd