###############################################################
#  Generated by:      Cadence Innovus 25.10-p002_1
#  OS:                Linux x86_64(Host ID tallinn.emse.fr)
#  Generated on:      Thu Aug 20 16:26:52 2026
#  Design:            fca2005
#  Command:           write_db /home/edu4chip_18/project_calendar/layout/fca2005_XH180/checkpoint/fca2005_2.enc
###############################################################
current_design fca2005
set_units -time 1ns -capacitance 1pf
#END OF CLOCK SECTION#
set_load -pin_load -max  0.045  [get_ports {weekday[7]}]
set_load -pin_load -min  0.045  [get_ports {weekday[7]}]
set_load -pin_load -max  0.045  [get_ports {weekday[6]}]
set_load -pin_load -min  0.045  [get_ports {weekday[6]}]
set_load -pin_load -max  0.045  [get_ports {weekday[5]}]
set_load -pin_load -min  0.045  [get_ports {weekday[5]}]
set_load -pin_load -max  0.045  [get_ports {weekday[4]}]
set_load -pin_load -min  0.045  [get_ports {weekday[4]}]
set_load -pin_load -max  0.045  [get_ports {weekday[3]}]
set_load -pin_load -min  0.045  [get_ports {weekday[3]}]
set_load -pin_load -max  0.045  [get_ports {weekday[2]}]
set_load -pin_load -min  0.045  [get_ports {weekday[2]}]
set_load -pin_load -max  0.045  [get_ports {weekday[1]}]
set_load -pin_load -min  0.045  [get_ports {weekday[1]}]
set_load -pin_load -max  0.045  [get_ports {weekday[0]}]
set_load -pin_load -min  0.045  [get_ports {weekday[0]}]
