# ####################################################################

#  Created by Genus(TM) Synthesis Solution 25.10-p002_1 on Thu Aug 20 17:39:57 CEST 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design top

set_load -pin_load 0.045 [get_ports tx]
set_clock_gating_check -setup 0.0 
set_wire_load_mode "enclosed"
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/DLY1HDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/DLY1HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/DLY2HDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/DLY2HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/DLY4HDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/DLY4HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/DLY8HDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/DLY8HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFQHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFQHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFQHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFQHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFRHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFRHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFRHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFRHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFRQHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFRQHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFRQHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFRQHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFRSHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFRSHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFRSHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFRSHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFRSQHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFRSQHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFRSQHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFRSQHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFSHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFSHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFSHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFSHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFSQHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFSQHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFSQHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFSQHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFR2HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFR2HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFR4HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFR4HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFR8HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFR8HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRQ2HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRQ2HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRQ4HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRQ4HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRQ8HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRQ8HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRQHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRQHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRQHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRQHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRR2HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRR2HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRR4HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRR4HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRR8HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRR8HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRQ2HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRQ2HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRQ4HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRQ4HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRQ8HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRQ8HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRQHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRQHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRQHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRQHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRSHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRSHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRSHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRSHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRSQHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRSQHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRSQHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRSQHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRSHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRSHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRSHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRSHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRSQHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRSQHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRSQHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRSQHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/CLKVBUFHD]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFQSSHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFQSSHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFQSSHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFQSSHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFRQSSHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFRQSSHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFRQSSHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFRQSSHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFSQSSHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFSQSSHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFSQSSHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFFSQSSHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRQSSHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRQSSHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRQSSHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRQSSHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRQSSHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRQSSHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRQSSHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRRQSSHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRSQSSHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRSQSSHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRSQSSHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_85C/SDFRSQSSHDX4]
